<?php

use Magento\Review\Block\Product\View\ListView;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;

/* @var ListView $block */
/* @var SecureHtmlRenderer $secureRenderer */
/* @var Escaper $escaper */

$items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($items)): ?>
    <div class="container mx-auto px-5 py-6 items-center" id="customer-reviews">
        <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
            <?php if (!$block->getHideTitle()): ?>
                <h3 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
                    <?= $escaper->escapeHtml(__('Customer Reviews')) ?>
                </h3>
            <?php endif ?>
        </div>
        <div class="card w-full px-6 py-3">
            <?php foreach ($items as $review): ?>
                <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                     class="border-b pb-4 my-4 border-container last:border-0 last:mb-0"
                >
                    <?php if (count($review->getRatingVotes())): ?>
                    <?php foreach ($review->getRatingVotes() as $vote): ?>
                    <?php
                    $rating = $vote->getPercent();
                    $ratingSteps = 5;
                    $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                    $starsEmpty = floor($ratingSteps - $starsFilled);
                    ?>
                    <div
                        itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        <div class="hidden">
                            <?= $escaper->escapeHtml($vote->getRatingCode()) ?>
                        </div>
                        <div class="flex flex-row">
                            <?php
                            $i = 0;
                            while ($i < $starsFilled) : ?>
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-yellow-400 w-6 h-6"
                                     viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path
                                        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
                                </svg>
                                <?php $i++; endwhile; ?>
                            <?php
                            $i = 0;
                            while ($i < $starsEmpty) : ?>
                                <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-gray-400 w-6 h-6"
                                     viewBox="0 0 20 20"
                                     fill="currentColor">
                                    <path
                                        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
                                </svg>
                                <?php $i++; endwhile; ?>
                        </div>
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="text-lg my-2" itemprop="name">
                        <?= $escaper->escapeHtml($review->getTitle()) ?>
                    </div>
                    <div>
                        <span><?= $escaper->escapeHtml(__('Review by')) ?></span>
                        <strong
                            itemprop="author"><?= $escaper->escapeHtml($review->getNickname()) ?></strong>
                        <span class="text-gray-700 inline-block ml-2">
                                <time
                                    itemprop="datePublished"
                                    datetime="<?= $escaper->escapeHtmlAttr(
                                        $block->formatDate(
                                            $review->getCreatedAt(),
                                            $format
                                        )
                                    ) ?>"><?= $escaper->escapeHtml(
                                        $block->formatDate($review->getCreatedAt(), $format)
                                    ) ?>
                                </time>
                            </span>
                    </div>
                    <div class="mt-2" itemprop="description">
                        <?= /* @noEscape */
                        nl2br($escaper->escapeHtml($review->getDetail())) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="toolbar review-toolbar mt-4">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
<?php endif; ?>
