<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */
?>
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
        <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0"><img class="object-cover object-center rounded" src="https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=500&amp;q=60" alt="hero"></div>
        <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">This is the Tailwind Theme for Magento</h1>
            <p class="mb-8 leading-relaxed">It's true. We can make Magento Theme development a happy place again.</p>
            <div class="flex justify-center"><button class="inline-flex btn btn-primary">Buy it</button> <button class="ml-4 inline-flex btn btn-secondary">Read more</button></div>
        </div>
    </div>
</section>
