<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$image1X = "https://images.unsplash.com/photo-1454111079122-eb76eb2d5754?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMzk2fQ&auto=format&fit=crop&w=1000&q=75";
$image2X = "https://images.unsplash.com/photo-1454111079122-eb76eb2d5754?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMzk2fQ&auto=format&fit=crop&w=1024&q=75";
$title = "This is the default Hyvä Theme.";
$content = "Hyvä themes are built with great technologies like TailwindCSS and AlpineJS.<br/> It's super light-weight and designed to be high performant and highly customizable.";
$link = "https://hyva.io/";
$cta = "Read more >";
?>
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 mt-8 lg:-mt-12 md:flex-row flex-col items-center">
        <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0"><img class="object-cover object-center rounded" src="https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=500&amp;q=60" alt="hero"></div>
        <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"><?= $title ?></h1>
            <p class="mb-8 leading-relaxed"><?= $content ?></p>
            <div class="flex justify-center">
                <a href="<?= $link ?>" class="inline-flex btn btn-primary">Buy it</a>
                <span class="flex self-center ml-4 ">or</span>
                <a href="<?= $link ?>" class="ml-4 inline-flex btn btn-secondary">Read more</a>
            </div>
        </div>
    </div>
</section>
