<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<small class="text-sm text-gray-800 sm:ml-6 sm:mt-0 mt-4">
    © 2020 Hyva Themes B.V. —
    <a
        href="https://twitter.com/hyva_io"
        target="_blank"
        rel="noopener noreferrer"
        class="text-gray-700 ml-1"
    >@hyva_io</a>
</small>
