<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$image = "https://images.unsplash.com/photo-1422190441165-ec2956dc9ecc?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=75";
$title = "Magento meets Tailwind";
$content = "";
$link = $block->getBaseUrl() . "products.html";
$cta = "Check our Products >";

$imageStyle = "background-image: url($image);";
?>

<section class="text-gray-700 body-font">
    <section class="w-full mx-auto flex pt-12 md:pt-0 items-center bg-cover bg-right h-64 min-h-50 md:min-h-50" style="<?= $imageStyle ?>">
        <div class="container mx-auto">
            <div class="flex flex-col w-full lg:w-1/2 justify-center items-start px-6 tracking-wide">
                <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"><?= $block->escapeHtml($title) ?></h1>
                <a class="btn btn-primary border border-primary" href="<?= $link ?>">
                    <?= $block->escapeHtml($cta) ?>
                </a>
            </div>
        </div>
    </section>
</section>

