<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$image1X = "https://images.unsplash.com/photo-1454111079122-eb76eb2d5754?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMzk2fQ&auto=format&fit=crop&w=1000&q=75";
$image2X = "https://images.unsplash.com/photo-1454111079122-eb76eb2d5754?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMzk2fQ&auto=format&fit=crop&w=1024&q=75";
$title = "Hyvä Themes";
$content = "We're making Magento Templates great again.";
$link = "https://hyva.io/";
$cta = "Read more >";

$imageStyle = "background-image: url($image1X); background-image: -webkit-image-set(url($image1X) 1x, url($image2X) 2x);";
?>

<section class="text-gray-700 body-font -mt-8">
    <section class="w-full mx-auto flex pt-8 md:pt-0 items-center bg-cover bg-right h-64 min-h-50 md:min-h-50 max-h-75" style="<?= $imageStyle ?>">
        <div class="container mx-auto">
            <div class="flex flex-col w-full lg:w-2/3 justify-center items-start px-6 tracking-wide">
                <h1 class="title-font text-4xl sm:text-5xl mb-4 font-medium text-white" style="text-shadow: 2px 2px 5px black"><?= $block->escapeHtml($title) ?></h1>
                <?php if($content) : ?>
                    <p class="text-2xl sm:text-3xl mb-4 font-medium text-white" style="text-shadow: 2px 2px 5px black"><?= $content ?></p>
                <?php endif; ?>
                <a class="btn btn-primary border border-primary" href="<?= $link ?>">
                    <?= $block->escapeHtml($cta) ?>
                </a>
            </div>
        </div>
    </section>
</section>

