<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Escaper $escaper */
/** @var Template $block */

$uniqueId = '_' . uniqid();
$title = (string) $block->getTitle();
$graphqlQuery = (string) ($block->getGraphqlQuery() ?? '');
$queryDataProcessorJsFunction = (string) ($block->getQueryDataProcessorJs() ?? '(data) => this.items = data');
$itemsJson = (string) ($block->getSliderItemsJson() ?? '[]');
$slideContentTemplateHtml = $block->getChildHtml('slider.item.template') ?: '';

?>
<script>
    function initSliderComponent<?= /** @noEscape */$uniqueId ?>() {
        return {
            active: 0,
            items: <?= /** @noEscape */ $itemsJson ?>,
            loading: true,
            minHeight() {
                return 'min-height: ' + ((this.loading && '491px') || 0);
            },
            <?php if ($graphqlQuery): ?>
            query: <?= /** @noEscape */ json_encode($graphqlQuery) ?>,
            getItems($nextTick) {
                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql?query=' + encodeURIComponent(
                    this.query
                ), {
                    method: 'GET',
                    headers: {
                        'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                    },
                })
                    .then((response) =>  response.json())
                    .then((data) => this.items = (<?= /** @noEscape */ $queryDataProcessorJsFunction ?>)(data, this))
                    .finally(() => {
                        this.loading = false;
                        $nextTick(() => this.calcPageSize());
                    });
            },
            <?php endif; ?>
            getSlider() {
                return this.$el.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.items.length / this.pageSize)
                    ) - this.items.length;
                }
            },
            calcActive(event) {
                const slider = this.getSlider();
                if (slider) {
                    this.active = Math.ceil(
                        Math.round(
                            slider.scrollLeft / (slider.scrollWidth / this.items.length)
                        ) / this.pageSize
                    ) * this.pageSize;
                }
            }
        }
    }

</script>
<section class="my-12 text-gray-700 body-font"
         x-data="initSliderComponent<?= /** @noEscape */ $uniqueId?>()"
    <?php if ($graphqlQuery): ?>
         x-init="getItems($nextTick);"
    <?php else: ?>
        x-init="calcPageSize();"
     <?php endif; ?>
         :style="minHeight()"
         @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
>
    <template x-if="items && items.length">
        <div class="container relative px-5">
            <?php if ($title): ?>
                <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                    border-gray-300 md:flex-row">
                    <h3 class="text-2xl font-medium text-gray-900 title-font">
                        <?= $escaper->escapeHtml($title); ?>
                    </h3>
                </div>
            <?php endif; ?>
            <div class="relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                     @scroll.debounce="calcActive"
                >
                    <template x-for="item in items">
                        <div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                            <div class="mx-1 card card-interactive">
                                 <?= $slideContentTemplateHtml ?>
                            </div>
                        </div>
                    </template>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <template x-if="items.length && items.length > pageSize">
                <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{ 'invisible' : active === 0 }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / items.length) * (active-pageSize); active=active-pageSize;">
                        <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                    </button>
                    <template x-for="(item, index) in items" :key="index">
                        <span class="flex-shrink-0 block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                    'bg-opacity-100': active === index,
                                    'hidden': (pageSize !== 1 && !!(index % pageSize))
                                    }"
                                @click="getSlider().scrollLeft =
                                    (getSlider().scrollWidth / items.length) * index; active=index;">
                        </span>
                    </template>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{ 'invisible' : active >= items.length-pageSize }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / items.length) * (active+pageSize); active=active+pageSize">
                        <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                    </button>
                </div>
            </template>
        </div>
    </template>
</section>
