<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var $viewModelStore Store */
$viewModelStore = $viewModels->require(Store::class);

/** @var Escaper $escaper */
/** @var Template $block */
$uniqueId = '_' . uniqid();
$query = $block->getGraphqlQuery();
/**
 * Can be a custom filter, like  "color: { in: [\"yellow\",\"orange\"] },"
 * @var string $productFilters
 */
$productFilters = $block->getProductFilters();
$categoryIds = $block->getCategoryIds();
$priceFrom = $block->getPriceFrom();
$priceTo = $block->getPriceTo();
$pageSize = $block->getPageSize() ?: '8';
$sortAttribute = $block->getSortAttribute() ?: 'position';
$sortDirection = $block->getSortDirection() ?: 'ASC';
$title = $block->getTitle();
$type = $block->getType() ?: "";

$linkedProduct = (in_array($type, ['related', 'crosssell', 'upsell']));

if ($linkedProduct) {
    if ($product = $block->getProduct()) {
        $productSkus = $block->getProduct()->getSku();
    } else {
        $productSkus = '';
    }
} else {
    $productSkus = $block->getProductSkus();
}

$productSkuFilter = $productSkus ?
    sprintf("sku: { in: [\"%s\"] },", join("\",\"", explode(',', $productSkus))) :
    "";

$categoryFilter = $categoryIds ?
    sprintf("category_id: { in: [\"%s\"] }", join("\",\"", explode(',', $categoryIds))) :
    "";
$priceFilter = $priceFrom || $priceTo ? "price: { from: \"$priceFrom\", to: \"$priceTo\" }," : "";

$productAttributes = "
      sku
      id
      name
      small_image {
        label
        url
      }
      url_key
      url_suffix
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
        }
      }";

$items = $linkedProduct ?
    "{$type}_products {
        $productAttributes
    }" :
    $productAttributes;

$graphqlQuery = $query ?: "
{
  products(
    filter: {
      $productFilters
      $productSkuFilter
      $categoryFilter
      $priceFilter
      }
    pageSize: {$pageSize},
    sort: {{$sortAttribute}: {$sortDirection}}
    ) {
    items {
        $items
    }
  },
  currency {
    base_currency_symbol
    base_currency_code
  }
}";
?>
<script defer>
    function initSliderComponent<?= /** @noEscape */$uniqueId ?>() {
        return {
            active: 0,
            products: [],
            currency: [],
            loading: true,
            minHeight: function minHeight() {
                return 'min-height: ' + ((this.loading && '491px') || 0);
            },
            query: <?= /** @noEscape */ json_encode($graphqlQuery) ?>,
            getProducts($nextTick) {
                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql?query=' + encodeURIComponent(
                    this.query
                ), {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                        'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                    },
                })
                    .then((response) =>  response.json())
                    .then((data) => {
                            this.currency = (data &&
                                data.data &&
                                data.data.currency);
                            <?php if ($linkedProduct): ?>
                            return this.products = (
                                data &&
                                data.data &&
                                data.data.products &&
                                data.data.products.items &&
                                data.data.products.items[0] &&
                                data.data.products.items[0]['<?= $escaper->escapeHtml($type) ?>_products']
                            ) || [];
                            <?php else: ?>
                            return this.products = (
                                data &&
                                data.data &&
                                data.data.products &&
                                data.data.products.items
                            ) || [];
                            <?php endif; ?>
                        }
                    ).finally(() => {
                        this.loading = false
                        $nextTick(() => this.calcPageSize());
                    });
            },
            addToWishlist(productId) {
                var formKey = document.querySelector('input[name=form_key]').value;
                var postUrl = BASE_URL+"wishlist/index/add/";
                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key="+ formKey + "&product="+productId+"&uenc="+btoa(window.location.href),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(function (response) {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "warning",
                                text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                            }], 5000
                        );
                    }
                }).then(function (response) {
                    if(!response) { return }
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: (response.success) ? "success" : "error",
                            text: (response.success)
                                ? "<?= $escaper->escapeHtml(__("%1 has been added to your Wish List.", __("Product"))) ?>"
                                : response.error_message
                        }], 5000
                    );
                    var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                    window.dispatchEvent(reloadCustomerDataEvent);
                }).catch(function (error) {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            },
            getSlider: function getSlider() {
                return this.$el.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize: function calcPageSize() {
                var slider = this.getSlider();
                if (slider) {
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.products.length / this.pageSize)
                    ) - this.products.length;
                }
            },
            calcActive: function calcActive(event) {
                var slider = this.getSlider();
                this.active = Math.ceil(
                    Math.round(
                        slider.scrollLeft / (slider.scrollWidth / this.products.length)
                    ) / this.pageSize
                ) * this.pageSize;
            },
            formatPrice(value, currency, showSign) {
                var formatter = new Intl.NumberFormat(
                    document.documentElement.lang,
                    {
                        style: 'currency',
                        currency: currency || this.currency.base_currency_code,
                        signDisplay: showSign ? "always" : "auto"
                    }
                );
                return (typeof Intl.NumberFormat.prototype.formatToParts) ?
                    formatter.formatToParts(value).map(({type, value}) => {
                        switch (type) {
                            case 'currency':
                                return this.currency.base_currency_symbol || value;
                            case 'minusSign':
                                return '- ';
                            case 'plusSign':
                                return '+ ';
                            default :
                                return value;
                        }
                    }).reduce((string, part) => string + part) :
                    formatter.format(value);
            },
        }
    }

</script>
<section class="my-12 text-gray-700 body-font"
         x-data="initSliderComponent<?= /** @noEscape */ $uniqueId?>()"
         x-init="getProducts($nextTick);"
         :style="minHeight()"
         @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
>
    <template x-if="products && products.length">
        <div class="container relative px-5">
            <?php if ($title): ?>
                <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                    border-gray-300 md:flex-row">
                    <h3 class="text-2xl font-medium text-gray-900 title-font">
                        <?= $escaper->escapeHtml($title); ?>
                    </h3>
                </div>
            <?php endif; ?>
            <div class="relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                     @scroll.debounce="calcActive"
                >
                    <template x-for="product in products">
                        <div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                            <div class="mx-1 card card-interactive">
                                <a :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                    product.url_key + product.url_suffix"
                                   class="relative flex items-center bg-white product photo product-item-photo"
                                   style="padding-top:100%"
                                   tabindex="-1">
                                    <span class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
                                        overflow-hidden align-center hover:shadow-sm">
                                        <img class="self-center w-full h-auto"
                                             :src="product.small_image.url"
                                             :alt="product.small_image.label"
                                             loading="lazy"
                                             width="500"
                                             height="500"
                                    />
                                    </span>
                                </a>

                                <p class="flex items-center justify-center px-1 pt-3 text-primary">
                                    <a class="truncate product-item-link"
                                        :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                            product.url_key + product.url_suffix"
                                       >
                                        <span x-text="product.name"></span>
                                    </a>
                                </p>
                                <p class="pt-1 text-lg text-center text-gray-900"
                                   x-text="formatPrice(
                                    product.price_range.minimum_price.final_price.value,
                                    product.price_range.minimum_price.final_price.currency
                                   )"></p>
                                <p class="flex flex-wrap inline p-3">
                                    <a class="justify-center w-auto mr-auto btn btn-primary"
                                       :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                            product.url_key + product.url_suffix">
                                        <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
                                    </a>
                                    <button
                                        aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                                        @click.prevent="addToWishlist(product.id)"
                                        class="inline-flex items-center justify-center w-10 h-10 p-0 ml-auto
                                        text-gray-500 bg-gray-200 border-0 rounded-full hover:text-red-600">
                                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                             stroke-width="2" class="w-5 h-5"
                                             viewBox="0 0 24 24">
                                            <path
                                                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78
                                                 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z">
                                            </path>
                                        </svg>
                                    </button>
                                </p>
                            </div>
                        </div>
                    </template>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <template x-if="products.length && products.length > pageSize">
                <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{ 'invisible' : active === 0 }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / products.length) * (active-pageSize)">
                        <svg viewBox="0 0 1024 1024">
                            <path class="path1"
                                  d="M716.8 1024c6.552 0 13.102-2.499 18.101-7.499 9.998-9.997 9.998-26.206
                                  0-36.203l-442.698-442.698 442.698-442.699c9.998-9.997 9.998-26.206
                                  0-36.203s-26.206-9.998-36.203 0l-460.8 460.8c-9.998 9.997-9.998 26.206
                                  0 36.203l460.8 460.8c5 5 11.55 7.499 18.102 7.499z">
                            </path>
                        </svg>
                    </button>
                    <template x-for="(product, index) in products" :key="index">
                        <span class="block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                    'bg-opacity-100': active === index,
                                    'hidden': (pageSize !== 1 && !!(index % pageSize))
                                    }"
                                @click="getSlider().scrollLeft =
                                    (getSlider().scrollWidth / products.length) * index">
                        </span>
                    </template>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{  'invisible' : active === products.length-pageSize }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / products.length) * (active+pageSize)">
                        <svg id="lnr-chevron-right" viewBox="0 0 1024 1024">
                            <path class="path1"
                                  d="M256 1024c-6.552 0-13.102-2.499-18.101-7.499-9.998-9.997-9.998-26.206
                                  0-36.203l442.698-442.698-442.698-442.699c-9.998-9.997-9.998-26.206
                                  0-36.203s26.206-9.998 36.203 0l460.8 460.8c9.998 9.997 9.998 26.206 0
                                  36.203l-460.8 460.8c-5 5-11.55 7.499-18.102 7.499z">
                            </path>
                        </svg>
                    </button>
                </div>
            </template>
        </div>
    </template>
</section>
