<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
$uniqueId = '_' . uniqid();
$query = $block->getGraphqlQuery();
/**
 * Can be a custom filter, like  "color: { in: [\"yellow\",\"orange\"] },"
 * @var string $productFilters
 */
$productFilters = $block->getProductFilters();
$categoryIds = $block->getCategoryIds();
$priceFrom = $block->getPriceFrom();
$priceTo = $block->getPriceTo();
$pageSize = $block->getPageSize() ?: '8';
$sortAttribute = $block->getSortAttribute() ?: 'position';
$sortDirection = $block->getSortDirection() ?: 'ASC';
$title = $block->getTitle();
$type = $block->getType() ?: "";

$linkedProduct = (in_array($type, ['related', 'crosssell', 'upsell']));
$productSkus = $linkedProduct ? $block->getProduct()->getSku() : $block->getProductSkus();

$productSkuFilter = $productSkus ? sprintf("sku: { in: [\"%s\"] },", join("\",\"", explode(',',$productSkus))) : "";
$categoryFilter = $categoryIds ? sprintf("category_id: { in: [\"%s\"] }", join("\",\"", explode(',',$categoryIds))) : "";
$priceFilter = $priceFrom || $priceTo ? "price: { from: \"$priceFrom\", to: \"$priceTo\" }," : "";

$productAttributes = "
      sku
      id
      name
      small_image {
        label
        url
      }
      url_key
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
        }
      }";

$items = $linkedProduct ?
    "{$type}_products {
        $productAttributes
    }" :
    $productAttributes;

$graphqlQuery = $query ?: "
{
  products(
    filter: {
      $productFilters
      $productSkuFilter
      $categoryFilter
      $priceFilter
      }
    pageSize: {$pageSize},
    sort: {{$sortAttribute}: {$sortDirection}}
    ) {
    items {
        $items
    }
  }
}";
?>
<script>
    function initSliderComponent<?= $uniqueId ?>() {
        return {
            active: 0,
            products: [],
            loading: true,
            get minHeight () {
                return this.loading && '443px' || 0;
            },
            query: `<?= $graphqlQuery ?>`,
            getProducts() {

                fetch('<?= $block->getBaseUrl() ?>graphql?query=' + encodeURIComponent(
                    this.query
                ), {
                    method: 'GET',
                    headers: {'Content-Type': 'application/json'},
                })
                    .then(response => response.json())
                    .then(
                        data => {
                            <?php if($linkedProduct): ?>
                            this.products = (data && data.data && data.data.products && data.data.products.items && data.data.products.items[0]['<?= $block->escapeHtml($type) ?>_products']) || [];
                            <?php else: ?>
                            this.products = (data && data.data && data.data.products && data.data.products.items) || [];
                            <?php endif; ?>
                        }
                    ).finally(() => { this.loading = false});
            }
        }
    }

</script>
<section class="text-gray-700 body-font my-12"
    x-data="initSliderComponent<?= $uniqueId?>()"
    x-init="getProducts();"
    :style="`min-height: ${minHeight}`"
>
    <template x-if="products && products.length">
        <div class="relative container px-5">
            <?php if ($title): ?>
                <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row flex-col items-center border-b-2 border-gray-300">
                    <h3 class="text-gray-900 text-2xl title-font font-medium">
                        <?= $block->escapeHtml($title); ?>
                    </h3>
                </div>
            <?php endif; ?>
            <div class="w-full relative overflow-x-hidden">
                <div class="js_slides w-full relative flex flex-no-wrap snap overflow-auto relative flex-no-wrap flex transition-all"
                     x-ref="slider<?= $uniqueId ?>"
                     x-on:scroll.debounce="active = Math.round($event.target.scrollLeft / ($event.target.scrollWidth / products.length))"
                >
                    <template x-for="product in products">
                        <div class="js_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none">
                            <div class="p-2 mr-2 rounded-md bg-background-lighter hover:bg-background">
                                <a :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                                   class="relative product photo product-item-photo flex items-center bg-white"
                                   style="padding-top:100%"
                                   tabindex="-1">
                                    <span class="absolute h-full w-full align-center top-0 left-0 flex content-center flex-wrap p-2 overflow-hidden">
                                        <img class="w-full h-auto"
                                         :src="product.small_image.url"
                                         :alt="product.small_image.label"
                                         loading="lazy"
                                         width="500"
                                         height="500"
                                    />
                                    </span>
                                </a>

                                <p class="pt-3 flex items-center justify-center text-primary px-1">
                                    <a class="product-item-link truncate"
                                        :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                                       >
                                        <span x-text="product.name"></span>
                                    </a>
                                </p>
                                <p class="pt-1 text-gray-900" x-text="new Intl.NumberFormat(document.documentElement.lang, { style: 'currency', currency: product.price_range.minimum_price.final_price.currency }).format(product.price_range.minimum_price.final_price.value)"></p>
                                <p class="p-3 flex flex-wrap inline">
                                    <a class="w-auto mr-auto btn btn-primary justify-center"
                                       :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'">
                                        <svg class="h-6 w-6 border-current inline" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                                        </svg>
                                        <span class="inline">Add to cart</span>
                                    </a>
                                    <button
                                        class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-auto">
                                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
                                             viewBox="0 0 24 24">
                                            <path
                                                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                                        </svg>
                                    </button>
                                </p>
                            </div>
                        </div>
                    </template>
                </div>
            </div>
            <template x-if="products.length">
                <div class="p-4 flex items-center justify-center flex-1">
                    <button
                        class="outline-none focus:outline-none rounded-full mx-4 text-black"
                        x-on:click=" $refs.slider<?= $uniqueId ?>.scrollLeft = $refs.slider<?= $uniqueId ?>.scrollLeft - ($refs.slider<?= $uniqueId ?>.scrollWidth / products.length)">
                        <
                    </button>
                    <template x-for="(product,index) in products" :key="index">
                        <button class="bg-black w-3 h-3 block mx-1 bg-opacity-25 shadow rounded-full"
                                x-bind:class="{'bg-opacity-100': active === index }"
                                x-on:click="$refs.slider<?= $uniqueId ?>.scrollLeft = ($refs.slider<?= $uniqueId ?>.scrollWidth / products.length) * index"></button>
                    </template>
                    <button
                        class="outline-none focus:outline-none rounded-full mx-4 text-black"
                        x-on:click="$refs.slider<?= $uniqueId ?>.scrollLeft = $refs.slider<?= $uniqueId ?>.scrollLeft + ($refs.slider<?= $uniqueId ?>.scrollWidth / products.length)">
                        >
                    </button>
                </div>
            </template>
        </div>
    </template>
</section>
