<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Escaper $escaper */
/** @var Template $block */

$uniqueId = '_' . uniqid();
$title = (string) $block->getTitle();
$items = (array) $block->getItems();
$sliderItemRenderer = $block->getChildBlock('slider.item.template');

?>
<script>
    function initSliderComponent<?= /** @noEscape */$uniqueId ?>() {
        return {
            active: 0,
            itemCount: <?= count($items) ?>,
            getSlider() {
                return this.$el.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive(event) {
                const slider = this.getSlider();
                if (slider) {
                    this.active = Math.ceil(
                        Math.round(
                            slider.scrollLeft / (slider.scrollWidth / this.itemCount)
                        ) / this.pageSize
                    ) * this.pageSize;
                }
            }
        }
    }

</script>
<section class="my-12 text-gray-700 body-font"
         x-data="initSliderComponent<?= /** @noEscape */ $uniqueId?>()"
         x-init="calcPageSize();"
         @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
>
    <?php if ($items): ?>
        <div class="container relative px-5">
            <?php if ($title): ?>
                <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                    border-gray-300 md:flex-row">
                    <h3 class="text-2xl font-medium text-gray-900 title-font">
                        <?= $escaper->escapeHtml($title); ?>
                    </h3>
                </div>
            <?php endif; ?>
            <div class="relative w-full overflow-x-hidden focus-within:ring-1 active:ring-0 ring-blue-500 ring-opacity-50">
                <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                     @scroll.debounce="calcActive"
                >
                    <?php foreach ($items as $item): ?>
                        <div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                            <div class="mx-1 card card-interactive">
                                 <?= $sliderItemRenderer->setItem($item)->toHtml() ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <template x-if="itemCount > pageSize">
                <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                        tabindex="-1"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{ 'invisible' : active === 0 }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / itemCount) * (active-pageSize); active=active-pageSize;">
                        <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                    </button>
                    <?php foreach (array_keys($items) as $idx): ?>
                        <span class="flex-shrink-0 block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                    'bg-opacity-100': active === <?= (int) $idx ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int) $idx ?> % pageSize))
                                    }"
                                @click="
                        getSlider().scrollLeft = (getSlider().scrollWidth / itemCount) * <?= (int) $idx ?>;
                        active=<?= (int) $idx ?>;
                                    ">
                        </span>
                    <?php endforeach; ?>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                        tabindex="-1"
                        class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                        :class="{ 'invisible' : active >= itemCount-pageSize }"
                        @click="getSlider().scrollLeft =
                            (getSlider().scrollWidth / itemCount) * (active+pageSize); active=active+pageSize">
                        <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                    </button>
                </div>
            </template>
        </div>
    <?php endif; ?>
</section>
