<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<script>
    async function getProducts(query,products) {

        let response = await fetch('<?= $block->getBaseUrl() ?>graphql?query=' + encodeURIComponent(
            query
        ), {
            method: 'GET',
            headers: {'Content-Type': 'application/json'},
        });
        let data = await response.json();

        return (data && data.data && data.data.products && data.data.products.items) || [];

    }
</script>
<section class="text-gray-700 body-font my-12"
    x-data='{ "products": [], query: `{
      products(filter: {price: {to: "1000"}}, pageSize: 8, sort: {position: ASC}) {
        items {
          sku
          id
          name
          small_image {
            label
            url
          }
          url_key
          price_range {
            minimum_price {
              regular_price {
                value
                currency
              }
              final_price {
                value
                currency
              }
            }
          }
        }
      }
    }`}'
    x-init="function() {
        getProducts(query).then(function (result) { products = result; $nextTick(function() { window.loadLorySliders() } ); })
    }"
>
    <div class="js_slider relative container"
    x-ref="target">
        <div class="js_frame w-full relative overflow-x-hidden">
            <div class="js_slides w-full relative flex flex-no-wrap" style="transition-timing-function: ease; transition-duration: 300ms; transform: translateX(0px);">
                <template x-for="product in products">
                    <div class="js_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none">
                        <div class="p-2 mr-2 rounded-md bg-gray-100 hover:bg-gray-200">
                            <a :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                               class="relative product photo product-item-photo flex items-center bg-white"
                               style="padding-top:100%"
                               tabindex="-1">
                                <span class="absolute h-full w-full align-center top-0 left-0 flex content-center flex-wrap p-2">
                                    <img class=""
                                     :src="product.small_image.url"
                                     :alt="product.small_image.label"
                                     loading="lazy"
                                     width="500"
                                     height="500"
                                />
                                </span>
                            </a>

                            <p class="pt-3 flex items-center justify-center text-primary px-1">
                                <a class="product-item-link truncate"
                                    :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'"
                                   >
                                    <span x-text="product.name"></span>
                                </a>

                            </p>
                            <p class="pt-1 text-gray-900" x-text="new Intl.NumberFormat(document.documentElement.lang, { style: 'currency', currency: product.price_range.minimum_price.final_price.currency }).format(product.price_range.minimum_price.final_price.value)"></p>
                            <p class="p-3 flex flex-wrap inline">
                                <a class="w-auto mr-auto btn btn-primary justify-center"
                                   :href="'<?= $block->getBaseUrl() ?>' + product.url_key + '.html'">
                                    <svg class="h-6 w-6 border-current" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                                    </svg>
                                    Add to cart
                                </a>
                                <a class="w-auto ml-auto btn btn-secondary h-12">
                                    <svg class="h-6 w-6 fill-current text-gray-500 hover:text-black" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                        <path d="M12,4.595c-1.104-1.006-2.512-1.558-3.996-1.558c-1.578,0-3.072,0.623-4.213,1.758c-2.353,2.363-2.352,6.059,0.002,8.412 l7.332,7.332c0.17,0.299,0.498,0.492,0.875,0.492c0.322,0,0.609-0.163,0.792-0.409l7.415-7.415 c2.354-2.354,2.354-6.049-0.002-8.416c-1.137-1.131-2.631-1.754-4.209-1.754C14.513,3.037,13.104,3.589,12,4.595z M18.791,6.205 c1.563,1.571,1.564,4.025,0.002,5.588L12,18.586l-6.793-6.793C3.645,10.23,3.646,7.776,5.205,6.209 c0.76-0.756,1.754-1.172,2.799-1.172s2.035,0.416,2.789,1.17l0.5,0.5c0.391,0.391,1.023,0.391,1.414,0l0.5-0.5 C14.719,4.698,17.281,4.702,18.791,6.205z"></path>
                                    </svg>
                                </a>
                            </p>
                        </div>
                    </div>
                </template>
            </div>
        </div>
        <span class="js_prev prev bg-white bg-opacity-75 hover:bg-opacity-100 disabled">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M302.67 90.877l55.77 55.508L254.575 250.75 358.44 355.116l-55.77 55.506L143.56 250.75z"></path></g></svg>
        </span>
        <span class="js_next next bg-white bg-opacity-75 hover:bg-opacity-100">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 501.5 501.5"><g><path fill="#2E435A" d="M199.33 410.622l-55.77-55.508L247.425 250.75 143.56 146.384l55.77-55.507L358.44 250.75z"></path></g></svg>
        </span>
    </div>
</section>
