<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Wrapper for product sections to include title
 *
 * @var Template $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$childHtml = $block->getChildHtml();
$sectionId = $block->getSectionId();
$sectionIdAttribute = $sectionId ? ' id="' . $escaper->escapeHtmlAttr($sectionId) . '"' : '';
?>
<?php if (trim($childHtml) !== ""): ?>
    <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300"<?= /* @noEscape */ $sectionIdAttribute ?>>
        <h2 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full"><?= $escaper->escapeHtml($block->getTitle()); ?></h2>
    </div>
    <div class="card w-full">
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>

