<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPrice;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var ProductPrice $productPrice */
$productPrice = $viewModels->require(ProductPrice::class);

$title = $block->getTitle() ?: __('Recently Viewed Products');

$widgetAttributesToShow = explode(',', (string) $block->getData('show_attributes'));
$widgetButtonsToShow = explode(',', (string) $block->getData('show_buttons'));
$widgetImageWidth = $block->getImageWidth() ?: 360;
$widgetImageHeight = $block->getImageHeight() ?: 360;

$jsTemplate = 'Magento_Catalog::product/widget/viewed/js/recently-viewed-products.phtml';
/* @noEscape */ echo $block->fetchView($block->getTemplateFile($jsTemplate));
?>
<div
    class="flow-root"
    x-data="initRecentlyViewedProductsComponent"
    x-defer="intersect"
    :style="minHeight"
>
    <template x-if="hasProducts">
        <div class="relative my-12">
            <h2 class="text-2xl font-medium mb-6">
                <?= $escaper->escapeHtml($title); ?>
            </h2>
            <div class="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
                <template x-for="product in products">
                    <div class="item product product-item card card-interactive grow flex flex-col w-full">
                        <?php if (in_array("image", $widgetAttributesToShow)): ?>
                            <a
                                :href="productUrl"
                                class="product photo product-item-photo block max-w-full mx-auto mb-3 no-animation"
                            >
                                <img
                                    :src="productImgUrl"
                                    :alt="productImgLabel"
                                    loading="lazy"
                                    width="<?= $escaper->escapeHtmlAttr($widgetImageWidth) ?>"
                                    height="<?= $escaper->escapeHtmlAttr($widgetImageHeight) ?>"
                                    class="product-image-photo object-contain"
                                    style="aspect-ratio: <?= $escaper->escapeHtmlAttr($widgetImageWidth . '/' . $widgetImageHeight) ?>"
                                >
                            </a>
                        <?php endif; ?>
                        <div class="product-info flex flex-col grow">
                            <?php if (in_array("name", $widgetAttributesToShow)): ?>
                                <p class="mt-2 mb-1 items-center justify-center font-semibold text-lg text-center">
                                    <a :href="productUrl" class="product-item-link">
                                        <span x-html="product.name"></span>
                                    </a>
                                </p>
                            <?php endif; ?>
                            <?php if (in_array("price", $widgetAttributesToShow)): ?>
                                <div class="price-container pt-1">
                                    <div class="price-box price-final_price">
                                        <span class="price-wrapper">
                                            <span class="price" x-text="productPrice"></span>
                                        </span>
                                    </div>
                                    <?php if ($productPrice->displayPriceInclAndExclTax()): ?>
                                        <template x-if="product.price_range.minimum_price.base_price">
                                            <div class="final-price-excl-tax">
                                                <span>
                                                    <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                                                    <span class="price" x-text="productTaxPrice"></span>
                                                </span>
                                            </div>
                                        </template>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <div class="mt-auto pt-3 flex flex-wrap items-center gap-y-4 gap-x-2">
                                <?php if (in_array("learn_more", $widgetAttributesToShow)): ?>
                                    <a :href="productUrl" class="btn btn-primary text-sm me-auto">
                                        <?= $escaper->escapeHtml(__('View Product')) ?>
                                    </a>
                                <?php endif; ?>
                                <div class="flex flex-wrap gap-2">
                                    <?php if ($wishlistViewModel->isEnabled() && in_array("add_to_wishlist", $widgetButtonsToShow)): ?>
                                        <button
                                            @click.prevent="addToWishlist"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                            type="button"
                                            class="btn p-2 rounded-full"
                                            data-addto="wishlist"
                                        >
                                            <?= $lucideIcons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                                        </button>
                                    <?php endif; ?>

                                    <?php if ($compareViewModel->showInProductList() && in_array("add_to_compare", $widgetButtonsToShow)): ?>
                                        <button
                                            @click.prevent="addToCompare"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                            type="button"
                                            class="btn p-2 rounded-full"
                                            data-addto="compare"
                                        >
                                            <?= $lucideIcons->scaleHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </template>
            </div>
        </div>
    </template>
</div>
