<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\Wishlist;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $viewModelProducts */
$viewModelProducts = $viewModels->require(ProductPage::class);

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Escaper $escaper */
/** @var Template $block */
$uniqueId = '_' . uniqid();
$query = $block->getGraphqlQuery();
$title = 'Recently Viewed Products';
$widgetAttrbutesToShow = explode(',', $this->getdata('show_attributes'));
$widgetButtonsToShow = explode(',', $this->getdata('show_buttons'));
?>
    <script>
        function initSliderComponent<?= /** @noEscape */$uniqueId ?>() {

            // Recently Viewed products Data being put into the local storage
            now = new Date();
            sku = '<?php echo $viewModelProducts->getProduct()->getSku(); ?>';
            productsExpiry = <?php echo $viewModelProducts->getRecentlyViewedLifeTime(); ?>;
            productsExpiry = productsExpiry * 1000;
            expiry = now.getTime() + productsExpiry;
            localStorageData = sku + ' ' + expiry;

            // localStorage.removeItem('recently_viewed_skus');

            if(localStorage.getItem('recently_viewed_skus')){
                // flush the local storage by getting rid of expired products
                cleanlocalStorageData = '';
                recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");
                recentlyViewedSkusArray.forEach(function myFunction(skuData,key){
                    tempSplitedArray  = skuData.split(" ");
                    if(now.getTime() < tempSplitedArray[1]){
                        cleanlocalStorageData = cleanlocalStorageData + ',' + tempSplitedArray[0] + ' ' + tempSplitedArray[1];
                    }
                });
                cleanlocalStorageData = cleanlocalStorageData.replace(/[,]/, '');
                localStorage.removeItem('recently_viewed_skus');
                localStorage.setItem('recently_viewed_skus', cleanlocalStorageData);
                recentlyViewedSkusArray = null;

                // avoind adding the already added sku in the local storage
                isExisted = false;
                recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");
                recentlyViewedSkusArray.forEach(function myFunction(skuData,key){
                    tempSplitedArray  = skuData.split(" ");
                    if(tempSplitedArray[0] == sku){
                        isExisted = true;
                    }
                });
                if(!isExisted){
                    localStorageData = localStorage.getItem('recently_viewed_skus') + ',' + localStorageData;
                    localStorage.setItem('recently_viewed_skus', localStorageData);
                }
            }else{
                localStorage.setItem('recently_viewed_skus', localStorageData);
            }

            return {
                active: 0,
                products: [],
                currency: [],
                currentProductSku: '<?php echo $viewModelProducts->getProduct()->getSku(); ?>',
                noOfProductsToShow: <?php echo $this->getData('page_size'); ?>,
                recentlyViewedLifetime: <?php echo $viewModelProducts->getRecentlyViewedLifeTime(); ?>,
                loading: true,
                minHeight() {
                    return 'min-height: ' + ((this.loading && '491px') || 0);
                },
                query: '',
                getProducts($nextTick) {
                    /* Fetching Products from local storage */
                    recentlyViewedSkusArray = localStorage.getItem('recently_viewed_skus').split(",");
                    recentlyViewedSkusArray = recentlyViewedSkusArray.reverse();
                    noOfProductsToShow = this.noOfProductsToShow;
                    currentProductSku = this.currentProductSku;
                    itemsToFetch = [];

                    recentlyViewedSkusArray.forEach(function myFunction(skuData,key){
                        tempSplitedArray  = skuData.split(" ");
                        /* avoid showing the current product */
                        if(tempSplitedArray[0] !== currentProductSku){
                            itemsToFetch[key] = tempSplitedArray[0];
                        }
                    });
                    if(!itemsToFetch.length){
                        this.noOfProductsToShow = 0;
                    }
                    itemsToFetch = JSON.stringify(itemsToFetch);
                    this.query = `{
                        products(
                            filter: {
                            
                            sku: { in: ${itemsToFetch} },
                            
                            
                            }
                            pageSize: ${this.noOfProductsToShow}
                            ) {
                            items {
                                
                            sku
                            id
                            name
                            small_image {
                                label
                                url
                            }
                            url_key
                            url_suffix
                            visibility
                            status
                            price_range {
                                minimum_price {
                                regular_price {
                                    value
                                    currency
                                }
                                final_price {
                                    value
                                    currency
                                }
                                }
                            }
                            }
                        }
                    }`;

                    fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql?query=' + encodeURIComponent(
                        this.query
                    ), {
                        method: 'GET',
                        headers: {
                            'Content-Type': 'application/json',
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                    })
                        .then((response) =>  response.json())
                        .then((data) => {
                                this.currency = (data &&
                                    data.data &&
                                    data.data.currency);
                                    return this.products = (
                                        data &&
                                        data.data &&
                                        data.data.products &&
                                        data.data.products.items
                                    ) || [];
                            }
                        ).finally(() => {
                        this.loading = false
                        $nextTick(() => this.calcPageSize());
                    });
                },
                addToWishlist(productId) {
                    var formKey = document.querySelector('input[name=form_key]').value;
                    var postUrl = BASE_URL+"wishlist/index/add/";
                    fetch(postUrl, {
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        },
                        "body": "form_key="+ formKey + "&product="+productId+"&uenc="+btoa(window.location.href),
                        "method": "POST",
                        "mode": "cors",
                        "credentials": "include"
                    }).then(function (response) {
                        if (response.redirected) {
                            window.location.href = response.url;
                        } else if (response.ok) {
                            return response.json();
                        } else {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "warning",
                                    text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                                }], 5000
                            );
                        }
                    }).then(function (response) {
                        if(!response) { return }
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: (response.success) ? "success" : "error",
                                text: (response.success)
                                    ? "<?= $escaper->escapeHtml(
                                        __("%1 has been added to your Wish List.", __("Product"))
                                    ) ?>" : response.error_message
                            }], 5000
                        );
                        var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                        window.dispatchEvent(reloadCustomerDataEvent);
                    }).catch(function (error) {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "error",
                                text: error
                            }], 5000
                        );
                    });
                },
                addToCompare(productId) {
                    const formKey = document.querySelector('input[name=form_key]').value;
                    const postUrl = BASE_URL + 'catalog/product_compare/add/';

                    fetch(postUrl, {
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                        },
                        "body": "form_key="+ formKey + "&product="+productId+"&uenc="+btoa(window.location.href),
                        "method": "POST",
                        "mode": "cors",
                        "credentials": "include"
                    }).then(function (response) {
                        if (response.redirected) {
                            window.location.href = response.url;
                        }
                    }).catch(function (error) {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "error",
                                text: error
                            }], 5000
                        );
                    });
                },
                getSlider() {
                    return this.$el.querySelector('.js_slides');
                },
                pageSize: 1,
                pageFillers: 0,
                calcPageSize() {
                    var slider = this.getSlider();
                    if (slider) {
                        this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                        this.pageFillers = (
                            this.pageSize * Math.ceil(this.products.length / this.pageSize)
                        ) - this.products.length;
                    }
                },
                calcActive(event) {
                    var slider = this.getSlider();
                    if (slider) {
                        this.active = Math.ceil(
                            Math.round(
                                slider.scrollLeft / (slider.scrollWidth / this.products.length)
                            ) / this.pageSize
                        ) * this.pageSize;
                    }
                }
            }
        }

    </script>



    <section class="my-12 text-gray-700 body-font"
            x-data="initSliderComponent<?= /** @noEscape */ $uniqueId?>()"
            x-init="getProducts($nextTick);"
            :style="minHeight()"
            @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
    >
        <template x-if="products && products.length">
            <div class="container relative px-5">
                <?php if ($title): ?>
                    <div class="container flex flex-col items-center pt-6 pb-3 mx-auto mb-6 border-b-2
                        border-gray-300 md:flex-row">
                        <h3 class="text-2xl font-medium text-gray-900 title-font">
                            <?= $escaper->escapeHtml($title); ?>
                        </h3>
                    </div>
                <?php endif; ?>
                <div class="relative w-full overflow-x-hidden">
                    <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                        @scroll.debounce="calcActive"
                    >
                        <template x-for="product in products">
                            <div class="flex-none w-full py-1 js_slide md:w-1/2 lg:w-1/3 xl:w-1/4">
                                <div class="mx-1 card card-interactive">
                                    <?php if(in_array("image", $widgetAttrbutesToShow)): ?>
                                        <a :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                            product.url_key + (product.url_suffix || '')"
                                        class="relative flex items-center bg-white product photo product-item-photo"
                                        style="padding-top:100%"
                                        tabindex="-1">
                                            <span class="absolute top-0 left-0 flex flex-wrap content-center w-full h-full p-2
                                                overflow-hidden align-center hover:shadow-sm">
                                                <img class="self-center w-full h-auto"
                                                    :src="product.small_image.url"
                                                    :alt="product.small_image.label"
                                                    loading="lazy"
                                                    width="500"
                                                    height="500"
                                                />
                                            </span>
                                        </a>
                                    <?php endif ?>
                                    <?php if(in_array("name", $widgetAttrbutesToShow)): ?>
                                        <p class="flex items-center justify-center px-1 pt-3 text-primary">
                                            <a class="truncate product-item-link"
                                            :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                                    product.url_key + (product.url_suffix || '')"
                                            >
                                                <span x-html="product.name"></span>
                                            </a>
                                        </p>
                                    <?php endif ?>
                                    <?php if(in_array("price", $widgetAttrbutesToShow)): ?>
                                        <p class="pt-1 text-lg text-center text-gray-900"
                                        x-text="hyva.formatPrice(product.price_range.minimum_price.final_price.value)"></p>
                                    <?php endif ?>
                                        <p class="flex flex-wrap gap-2 inline p-3">
                                            <?php if(in_array("learn_more", $widgetAttrbutesToShow)): ?>
                                                <a class="justify-center w-auto mr-auto btn btn-primary"
                                                :href="'<?= $escaper->escapeUrl($block->getBaseUrl()) ?>' +
                                                        product.url_key + (product.url_suffix || '')">
                                                    <span class="inline"><?= $escaper->escapeHtml(__('View Product')) ?></span>
                                                </a>
                                            <?php endif ?>
                                            <span class="inline-flex gap-2">
                                                <?php if (in_array("add_to_compare", $widgetButtonsToShow)): ?>
                                                    <?php if ($compareViewModel->showInProductList()): ?>
                                                        <button @click.prevent="addToCompare(product.id)"
                                                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                                class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex
                                                                items-center justify-center text-gray-500 hover:text-yellow-500"
                                                        >
                                                        <?= $heroicons->scaleHtml("w-5 h-5") ?>
                                                    </button>
                                                    <?php endif; ?>
                                                <?php endif ?>
                                                <?php if (in_array("add_to_wishlist", $widgetButtonsToShow)): ?>
                                                    <?php if ($wishlistViewModel->isEnabled()): ?>
                                                        <button
                                                            aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                                                            @click.prevent="addToWishlist(product.id)"
                                                            class="inline-flex items-center justify-center w-10 h-10 p-0 ml-auto
                                                        text-gray-500 bg-gray-200 border-0 rounded-full hover:text-red-600"
                                                        >
                                                        <?= $heroicons->heartHtml("w-5 h-5", 25, 25) ?>
                                                    </button>
                                                    <?php endif; ?>
                                                <?php endif ?>
                                            </span>
                                        </p>
                                </div>
                            </div>
                        </template>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 0
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 1
                            }"></div>
                        <div :class="{
                            'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/4 flex-none py-1' : pageFillers > 2
                            }"></div>
                    </div>
                </div>
                <template x-if="products.length && products.length > pageSize">
                    <div class="flex items-center justify-center flex-1 p-4" x-cloak>
                        <button
                            aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                            class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                            :class="{ 'invisible' : active === 0 }"
                            @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / products.length) * (active-pageSize); active=active-pageSize;">
                            <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                        </button>
                        <template x-for="(product, index) in products" :key="index">
                            <span class="flex-shrink-0 block w-3 h-3 mx-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                        'bg-opacity-100': active === index,
                                        'hidden': (pageSize !== 1 && !!(index % pageSize))
                                        }"
                                @click="getSlider().scrollLeft =
                                        (getSlider().scrollWidth / products.length) * index; active=index;">
                            </span>
                        </template>
                        <button
                            aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                            class="w-8 h-8 mx-4 text-black rounded-full outline-none focus:outline-none"
                            :class="{ 'invisible' : active >= products.length-pageSize }"
                            @click="getSlider().scrollLeft =
                                (getSlider().scrollWidth / products.length) * (active+pageSize); active=active+pageSize">
                            <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                        </button>
                    </div>
                </template>
            </div>
        </template>
    </section>