<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPrice;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var ProductPrice $productPrice */
$productPrice = $viewModels->require(ProductPrice::class);

$widgetAttributesToShow = explode(',', (string) $block->getData('show_attributes'));
$widgetButtonsToShow = explode(',', (string) $block->getData('show_buttons'));
$pageSize = $block->getData('page_size') ?? 3;

$jsTemplate = 'Magento_Catalog::product/widget/viewed/js/recently-viewed-products.phtml';
/* @noEscape */ echo $block->fetchView($block->getTemplateFile($jsTemplate));
?>
<div
    x-data="initRecentlyViewedProductsComponent"
    x-defer="intersect"
    data-products-to-show="<?= $escaper->escapeHtmlAttr($pageSize) ?>"
    class="min-h-80"
>
    <template x-if="hasProducts">
        <div class="mt-8">
            <h2 class="border-t border-gray-300 mb-6 pt-5 font-semibold text-lg">
                <?= $escaper->escapeHtml(__('Recently Viewed Products')); ?>
            </h2>
            <ul role="list">
                <template x-for="product in products">
                    <li class="flex gap-4 items-start mb-4">
                        <?php if (in_array("image", $widgetAttributesToShow)): ?>
                            <a
                                :href="productUrl"
                                class="block shrink-0 mb-3"
                            >
                                <img
                                    :src="product.small_image.url"
                                    :alt="product.small_image.label"
                                    loading="lazy"
                                    width="40"
                                    height="40"
                                >
                            </a>
                        <?php endif; ?>
                        <div class="product-item-details">
                            <?php if (in_array("name", $widgetAttributesToShow)): ?>
                                <p class="text-sm">
                                    <a :href="productUrl" x-html="product.name"></a>
                                </p>
                            <?php endif; ?>
                            <?php if (in_array("price", $widgetAttributesToShow)): ?>
                                <div class="price-container pt-1">
                                    <div class="price-box price-final_price">
                                        <span class="price-wrapper">
                                            <span class="price" x-text="productPrice"></span>
                                        </span>
                                    </div>
                                    <?php if ($productPrice->displayPriceInclAndExclTax()): ?>
                                        <template x-if="product.price_range.minimum_price.base_price">
                                            <div class="final-price-excl-tax">
                                                <span>
                                                    <span><?= $escaper->escapeHtml(__('Excl. Tax')) ?>:</span>
                                                    <span class="price" x-text="productTaxPrice"></span>
                                                </span>
                                            </div>
                                        </template>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <div class="mt-auto pt-3 flex flex-wrap items-center gap-y-4 gap-x-2">
                                <?php if (in_array("learn_more", $widgetAttributesToShow)): ?>
                                    <a :href="productUrl" class="btn text-sm me-auto">
                                        <?= $escaper->escapeHtml(__('View Product')) ?>
                                    </a>
                                <?php endif; ?>
                                <div class="flex flex-wrap gap-2">
                                    <?php if ($wishlistViewModel->isEnabled() && in_array("add_to_wishlist", $widgetButtonsToShow)): ?>
                                        <button
                                            @click.prevent="addToWishlist"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                            type="button"
                                            class="btn p-2 rounded-full"
                                            data-addto="wishlist"
                                        >
                                            <?= $lucideIcons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                                        </button>
                                    <?php endif; ?>

                                    <?php if ($compareViewModel->showInProductList() && in_array("add_to_compare", $widgetButtonsToShow)): ?>
                                        <button
                                            @click.prevent="addToCompare"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                            type="button"
                                            class="btn p-2 rounded-full"
                                            data-addto="compare"
                                        >
                                            <?= $lucideIcons->scaleHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
                                        </button>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                </template>
            </ul>
        </div>
    </template>
</div>
