<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @deprecated
 *
 * Everything is now handled in the product-slider.phtml
 * Skipping the need to split the Slider and the Product List item dependency loader logic.
 *
 * This file is kept here to prevent loading errors, but is planned for removal in version 1.5
 */

declare(strict_types=1);
?>
