<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Checkout\Block\Cart\Coupon;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;

/** @var Coupon $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = (bool) strlen($block->getCouponCode() ?: "");
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<script>
    function initCouponForm() {
        return {
            errors: 0,
            hasCaptchaToken: 0,
            showCouponForm: <?= $hasCouponCode ? 1 : 0 ?>,
            formData: {
                coupon_code: '<?= $escaper->escapeJs($block->getCouponCode()) ?>',
                remove: '<?= (int) $hasCouponCode ?>'
            },
            init(){
                const browserStorageShowCouponForm = hyva.getBrowserStorage().getItem('hyva.showCouponForm');
                this.showCouponForm = browserStorageShowCouponForm === 'true' ? true : false;
            },
            toggleShowCoupon() {
                this.showCouponForm = !this.showCouponForm;

                hyva.getBrowserStorage().setItem('hyva.showCouponForm', this.showCouponForm);

                this.$nextTick(() => this.$refs.couponInput.select());
            },
            submitForm() {
                const $form = document.querySelector('#discount-coupon-form');
                <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_COUPON_CODE) : '' ?>

                if (this.errors === 0) {
                    hyva.postCart($form);
                }
            }
        }
    };
</script>
<details
    class="coupon-form group"
    x-data="initCouponForm()"
    :open="showCouponForm"
>
    <summary
        @click.prevent="toggleShowCoupon"
        class="flex justify-between items-center gap-2 py-2 border-b-2 border-gray-300 font-semibold cursor-pointer [&::-webkit-details-marker]:hidden"
    >
        <span><?= $escaper->escapeHtml(__('Apply Discount Code')) ?></span>
        <?= $heroicons->chevronDownHtml('transform group-open:rotate-180', 18, 18, ['aria-hidden' => 'true']); ?>
    </summary>
    <div>
        <form
            id="discount-coupon-form"
            class="card my-4"
            action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>"
            method="post"
            @submit.prevent="submitForm()"
        >
            <?= $block->getBlockHtml('formkey') ?>
            <?php if (!$hasCouponCode): ?>
                <input type="hidden" name="remove" id="remove-coupon" value="1">
            <?php endif ?>
            <label for="coupon_code" class="label sr-only">
                <?= $escaper->escapeHtml(__('Enter discount code')) ?>
            </label>
            <div class="flex flex-col gap-2">
                <div class="control">
                    <input
                        type="text"
                        class="form-input w-full disabled:opacity-75 disabled:bg-gray-100 disabled:cursor-not-allowed"
                        id="coupon_code"
                        name="coupon_code"
                        value="<?= $escaper->escapeHtmlAttr($block->getCouponCode()) ?>"
                        x-model="formData.coupon_code"
                        x-ref="couponInput"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Enter discount code')) ?>"
                        required
                        <?php if ($hasCouponCode): ?>
                            disabled
                        <?php endif; ?>
                    >
                </div>
                <?php if (!$hasCouponCode): ?>
                    <button type="submit" class="btn btn-primary" value="<?= $escaper->escapeHtmlAttr(__('Apply Discount')) ?>">
                        <?= $escaper->escapeHtml(__('Apply Discount')) ?>
                    </button>
                <?php else: ?>
                    <button type="submit" class="btn btn-primary" value="<?= $escaper->escapeHtmlAttr(__('Cancel Coupon')) ?>">
                        <?= $escaper->escapeHtml(__('Cancel Coupon')) ?>
                    </button>
                <?php endif; ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_COUPON_CODE) : '' ?>
                <?php if ($recaptcha && $legalNoticeHtml = $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_COUPON_CODE)): ?>
                    <div class="w-full">
                        <?= $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_COUPON_CODE) ?>
                    </div>
                <?php endif; ?>
            </div>
        </form>
    </div>
</details>

