<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="flex flex-col lg:flex-row-reverse lg:items-start gap-8">
    <div class="card lg:w-80 2xl:w-96 lg:sticky lg:top-2">
        <h2 class="text-xl font-bold">
            <?= $escaper->escapeHtml(__('Summary')) ?>
        </h2>
        <?= $block->getChildHtml('cart.discount') ?>
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
    <div class="lg:flex-1">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
</div>
