<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Header\Logo;

/**
 * @var Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>
<a class="flex items-center justify-center tracking-wide no-underline hover:no-underline font-medium font-title text-gray-800 text-xl"
   href="<?= $block->escapeUrl($block->getUrl('')) ?>"
   title="<?= $block->escapeHtmlAttr($storeName) ?>"
   aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
        <?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : 'width="200"' ?>
        <?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : 'height="150"' ?>
    />
    <?= $block->escapeHtml($storeName) ?>
</a>
