<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;

/** @var Template $block */
/** @var SearchHelper $helper */

$helper = $this->helper(SearchHelper::class);
?>
<div class="container mx-auto py-2 text-black">
    <form class="form minisearch" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $block->escapeHtml(__('Search')) ?></span>
        </label>
        <input id="search"
               x-ref="searchInput"
               type="search"
               name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
               value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
               placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
               maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
               class="w-full text-grey-800 transition focus:outline-none focus:border-transparent p-2 appearance-none leading-normal text-lg lg:text-xl"
        />
    </form>
</div>
