<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\CustomerRegistration;
use Magento\Customer\Block\Account\Customer;
use Magento\Customer\Model\Account\Redirect;
use Magento\Framework\Escaper;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var CustomerRegistration $customerRegistration */
$customerRegistration = $viewModels->require(CustomerRegistration::class);
?>

<div
    class="relative inline-block ml-1 sm:ml-3"
    x-data="{ open: false }"
    @keyup.escape="open = false"
>
    <button
        type="button"
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl('customer/account'))) ?>"
        id="customer-menu"
        class="block hover:text-black"
        @click="open = !open"
        @click.outside="open = false"
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
        aria-haspopup="true"
    >
        <?= $heroicons->userHtml('md:h-6 md:w-6', 32, 32, ['aria-hidden' => 'true']); ?>
    </button>
    <nav
        class="
            absolute right-0 z-20 w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
            shadow-lg sm:w-48 lg:mt-3 bg-container-lighter
        "
        x-cloak
        x-show="open"
        aria-labelledby="customer-menu"
        @click.outside="open = false"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Account')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Wish List')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
            >
                <?= $escaper->escapeHtml(__('My Orders')); ?>
            </a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Address Book')); ?></a>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/logout')) ?>"
            >
                <?= $escaper->escapeHtml(__('Sign Out')); ?>
            </a>
        <?php else: ?>
            <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
               onclick="hyva.setCookie && hyva.setCookie(
                   '<?= /** @noEscape */ Redirect::LOGIN_REDIRECT_URL ?>',
                   window.location.href,
                   1
                   )"
               href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>">
                <?= $escaper->escapeHtml(__('Sign In')); ?>
            </a>
            <?php if ($customerRegistration->isAllowed()): ?>
                <a class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                   href="<?= $escaper->escapeUrl($block->getUrl('customer/account/create')) ?>"
                >
                    <?= $escaper->escapeHtml(__('Create an Account')); ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </nav>
</div>
