<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="flex flex-col pb-2 my-2 border-b-2 border-gray-300 estimate-shipping-form">
    <div class="flex">
        <span @click="toggleEstimateShipping"
              class="flex justify-between w-full font-semibold whitespace-nowrap cursor-pointer select-none text-primary-lighter"
        >
            <span x-show="cartData.is_virtual">
                <?= $escaper->escapeHtml(__('Estimate Tax')) ?>
            </span>
            <span x-show="! cartData.is_virtual">
                <?= $escaper->escapeHtml(__('Estimate Shipping and Tax')) ?>
            </span>
            <span :class="{ 'rotate-180' : showEstimateShipping}" class="block transform">
                <?= $heroicons->chevronDownHtml('w-6 h-6', 25, 25) ?>
            </span>
        </span>
    </div>
    <div x-show="showEstimateShipping" class="mt-2">
        <div class="mt-2" x-show="! cartData.is_virtual">
            <?= $escaper->escapeHtml(__('Enter your destination to get a shipping estimate.')) ?>
        </div>
        <div class="mt-2" x-show="cartData.is_virtual">
            <?= $escaper->escapeHtml(__('Enter your billing address to get a tax estimate.')) ?>
        </div>
        <form id="estimate-shipping-form"
              class="block my-4 card"
              x-show="showEstimateShipping"
              @submit.prevent=""
        >
            <template x-if="getSortedCountryCodes().length === 1">
                <input id="region" placeholder="<?= $escaper->escapeHtmlAttr(__('Region')) ?>"
                       :value="countries[getEstimationCountry()].name"
                       disabled
                       class="p-2 w-full form-input"/>
            </template>
            <template x-if="getSortedCountryCodes().length > 1">
                <div>
                    <label for="country"><?= $escaper->escapeHtml(__('Country')) ?></label>
                    <select id="country"
                            @change="selectEstimationCountry($event.target.value)"
                            class="w-full form-input form-select">
                        <template x-for="countryId in getSortedCountryCodes()" :key="countryId">
                            <option :value="countryId"
                                    :selected="getEstimationCountry() === countryId"
                                    x-text="countries[countryId].name"
                            ></option>
                        </template>
                    </select>
                </div>
            </template>
            <label for="region" class="pt-2"><?= $escaper->escapeHtml(__('State/Region')) ?></label>
            <template x-if="countries[getEstimationCountry()].regions">
                <select id="region"
                        @change="selectEstimationRegionId($event.target.value)"
                        class="w-full form-input">
                    <template x-for="id in getSortedRegionIds(getEstimationCountry())" :key="id">
                        <option :value="id"
                                :selected="getEstimationRegionId() == id"
                                x-text="countries[getEstimationCountry()].regions[id].name"></option>
                    </template>
                </select>
            </template>
            <template x-if="! countries[getEstimationCountry()].regions">
                <input id="region" placeholder="<?= $escaper->escapeHtmlAttr(__('Region')) ?>"
                       :value="getEstimationRegionName()"
                       @change="selectEstimationRegionName($event.target.value)"
                       class="p-2 w-full form-input"/>
            </template>
            <label for="postcode" class="pt-2"><?= $escaper->escapeHtml(__('Postcode')) ?></label>
            <input id="postcode"
                   :value="getEstimationPostcode()"
                   @change="selectEstimationPostcode($event.target.value)"
                   @input.debounce.1000="selectEstimationPostcode($event.target.value)"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Postcode')) ?>"
                   class="p-2 w-full form-input"/>
            <div class="fieldset lg:hidden">
                <div class="flex flex-col gap-2 justify-center sm:flex-row md:justify-start">

                    <button class="justify-center mt-4 btn btn-primary md:text-sm lg:text-base" type="button"
                        @click.stop="estimateShippingRequest">

                        <span x-show="! cartData.is_virtual">
                            <?= $escaper->escapeHtml(__('Estimate shipping')) ?>
                        </span>
                        <span x-show="cartData.is_virtual">
                            <?= $escaper->escapeHtml(__('Estimate tax')) ?>
                        </span>
                    </button>
                </div>
            </div>
            <template x-if="getEstimatedShippingRateCarriers().length > 0">
                <div class="pt-2">
                    <template x-for="carrier in getEstimatedShippingRateCarriers()" :key="carrier">
                        <div>
                            <div class="font-bold" x-text="carrier"></div>
                            <template x-for="rate in getRatesForCarrier(carrier)" :key="rate">
                                <label class="flex items-center">
                                    <input class="mr-2" type="radio"
                                           :value="rate.carrier_code + '_' + rate.method_code"
                                           x-model="selectedShippingRate"
                                           @change="selectShippingRate(rate)"/>
                                    <div class="grid grid-cols-2 w-full">
                                        <div x-text="rate.method_title"></div>
                                        <div x-text="hyva.formatPrice(rate.price_excl_tax.value)"></div>
                                    </div>
                                </label>
                            </template>
                        </div>
                    </template>
                </div>
            </template>
            <template x-if="estimatedShippingRatesLoading && ! cartData.is_virtual">
                <div class="pt-2"><?= $escaper->escapeHtml(__('Loading rates...')) ?></div>
            </template>
        </form>
    </div>
</div>
