<?php declare(strict_types=1);

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

?>
<div class="estimate-shipping-form">
    <div class="flex justify-center md:justify-start">
        <span @click="toggleEstimateShipping"
              class="cursor-pointer text-primary-lighter select-none whitespace-nowrap"
        >
            <span class="underline" x-show="cartData.is_virtual">
                <?= $block->escapeHtml(__('Estimate Tax')) ?>
            </span>
            <span class="underline" x-show="! cartData.is_virtual">
                <?= $block->escapeHtml(__('Estimate Shipping and Tax')) ?>
            </span>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" class="w-4 h-4 inline-block ml-2"
                 viewBox="0 0 24 24" stroke="currentColor">
                <path x-show="!showEstimateShipping" stroke-linecap="round" stroke-linejoin="round"
                      stroke-width="2" d="M19 9l-7 7-7-7"/>
                <path x-show="showEstimateShipping" stroke-linecap="round" stroke-linejoin="round"
                      stroke-width="2" d="M5 15l7-7 7 7"/>
            </svg>
        </span>
    </div>
    <div x-show="showEstimateShipping">
        <div class="mt-2" x-show="! cartData.is_virtual">
            <?= $escaper->escapeHtml(__('Enter your destination to get a shipping estimate.')) ?>
        </div>
        <div class="mt-2" x-show="cartData.is_virtual">
            <?= $escaper->escapeHtml(__('Enter your billing address to get a tax estimate.')) ?>
        </div>
        <form id="estimate-shipping-form"
              class="block my-4 card"
              x-show="showEstimateShipping"
              @submit.prevent=""
        >
            <template x-if="getSortedCountryCodes().length === 1">
                <input id="region" placeholder="<?= $escaper->escapeHtmlAttr(__('Region')) ?>"
                       :value="countries[getEstimationCountry()].name"
                       disabled
                       class="w-full form-input p-2"/>
            </template>
            <template x-if="getSortedCountryCodes().length > 1">
                <label for="country"><?= $escaper->escapeHtml(__('Country')) ?></label>
                <select id="country"
                        @change="selectEstimationCountry($event.target.value)"
                        class="w-full form-input form-select">
                    <template x-for="countryId in getSortedCountryCodes()" :key="countryId">
                        <option :value="countryId"
                                :selected="getEstimationCountry() === countryId"
                                x-text="countries[countryId].name"
                        ></option>
                    </template>
                </select>
            </template>
            <label for="region" class="pt-2"><?= $escaper->escapeHtml(__('State/Region')) ?></label>
            <template x-if="countries[getEstimationCountry()].regions">
                <select id="region"
                        @change="selectEstimationRegionId($event.target.value)"
                        class="w-full form-input">
                    <template x-for="id in getSortedRegionIds(getEstimationCountry())" :key="id">
                        <option :value="id"
                                :selected="getEstimationRegionId() == id"
                                x-text="countries[getEstimationCountry()].regions[id].name"></option>
                    </template>
                </select>
            </template>
            <template x-if="! countries[getEstimationCountry()].regions">
                <input id="region" placeholder="<?= $escaper->escapeHtmlAttr(__('Region')) ?>"
                       :value="getEstimationRegionName()"
                       @change="selectEstimationRegionName($event.target.value)"
                       class="w-full form-input p-2"/>
            </template>
            <label for="postcode" class="pt-2"><?= $escaper->escapeHtml(__('Postcode')) ?></label>
            <input id="postcode"
                   :value="getEstimationPostcode()"
                   @change="selectEstimationPostcode($event.target.value)"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Postcode')) ?>"
                   class="w-full form-input p-2"/>
            <div class="fieldset lg:hidden">
                <div class="flex flex-col sm:flex-row gap-2 justify-center md:justify-start">

                    <button class="btn btn-primary md:text-sm lg:text-base justify-center mt-4" type="button"
                        @click.stop="estimateShippingRequest">

                        <span x-show="! cartData.is_virtual">
                            <?= $escaper->escapeHtml(__('Estimate shipping')) ?>
                        </span>
                        <span x-show="cartData.is_virtual">
                            <?= $escaper->escapeHtml(__('Estimate tax')) ?>
                        </span>
                    </button>
                </div>
            </div>
            <template x-if="getEstimatedShippingRateCarriers().length > 0">
                <div class="pt-2">
                    <template x-for="carrier in getEstimatedShippingRateCarriers()" :key="carrier">
                        <div>
                            <div class="font-bold" x-text="carrier"></div>
                            <template x-for="rate in getRatesForCarrier(carrier)" :key="rate">
                                <label class="flex items-center">
                                    <input class="mr-1.5" type="radio"
                                           :value="rate.carrier_code + '_' + rate.method_code"
                                           x-model="selectedShippingRate"
                                           @change="selectShippingRate(rate)"/>
                                    <div class="grid grid-cols-2 w-full">
                                        <div x-text="rate.method_title"></div>
                                        <div x-text="hyva.formatPrice(rate.price_excl_tax.value)"></div>
                                    </div>
                                </label>
                            </template>
                        </div>
                    </template>
                </div>
            </template>
            <template x-if="estimatedShippingRatesLoading && ! cartData.is_virtual">
                <div class="pt-2"><?= $escaper->escapeHtml(__('Loading rates...')) ?></div>
            </template>
        </form>
    </div>
</div>
