<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

?>
<?php
/** @var \Magento\Checkout\Block\Cart $block */
?>
<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
<template x-if="cartData && cartData.available_payment_methods && cartData.available_payment_methods.length">
    <div class="flex flex-wrap items-baseline justify-center lg:justify-end space-x-4 space-y-2">
        <?php foreach ($methods as $method): ?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== ''): ?><?= /* @noEscape */
                $methodHtml ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</template>
