<?php

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var $block Template */
/** @var $escaper Escaper */

?>
<template x-if="!isLoading && cartEmpty === true">
    <div>
        <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
        <p><?= $block->escapeHtml(__('You have no items in your shopping cart.')) ?></p>
        <p><?= $escaper->escapeHtml(
                __(
                    'Click <a href="%1">here</a> to continue shopping.',
                    $escaper->escapeUrl('')
                ),
                ['a']
            ) ?>
        </p>
        <?= $block->getChildHtml('shopping.cart.table.after') ?>
    </div>
</template>
