<footer class="text-gray-700 body-font bg-gray-200 border shadow pb-16">
    <div class="container px-5 py-8 mx-auto">
        <div class="flex flex-wrap md:text-left text-center order-first">
            <?= $block->getChildHtml() ?>
        </div>
    </div>
    <div class="bg-gray-100 border">
        <div class="container px-5 py-6 mx-auto flex items-center sm:flex-row flex-col">
            <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
                <span class="ml-3 text-xl">Tailwind Theme</span>
            </a>
            <p class="text-sm text-gray-500 sm:ml-6 sm:mt-0 mt-4">
                © 2020 wigman —
                <a class="text-gray-600 ml-1" href="https://twitter.com/willemwigman" target="_blank" rel="noopener noreferrer">@willemwigman</a>
            </p>
        </div>
    </div>
</footer>

