<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    function initHeader () {
        return {
            menuOpen: false,
            searchOpen: false,
            cart: {},
            getCart (data) {
                if (data.cart) { this.cart = data.cart }
            }
        }
    }
</script>
<nav id="header"
     class="w-full z-30 bg-background shadow"
     x-data="initHeader()"
     @keydown.window.escape="searchOpen = false; menuOpen = false"
     @private-content-loaded.window="getCart($event.detail.data)"
>
    <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-6 py-3">

        <label for="menu-toggle" class="cursor-pointer md:hidden block order-2 sm:order-1"
               @click="menuOpen = !menuOpen"
               :class="{ 'transition transform-180': menuOpen }"
        >
            <svg class="fill-current text-gray-900" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
                <title>menu</title>
                <path x-show="menuOpen" fill-rule="evenodd" clip-rule="evenodd" d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z"></path>
                <path x-show="!menuOpen" d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
            </svg>
        </label>
        <input class="hidden" type="checkbox" id="menu-toggle">

        <div class="md:flex md:items-center md:w-auto w-full order-3 md:order-1" id="menu"
             :class="{ 'block': menuOpen, 'hidden': !menuOpen }"
             @click.away="menuOpen = false"
             x-show="true"
        >
            <nav>
                <ul class="md:flex items-center justify-between text-base text-gray-700 pt-4 md:pt-0">
                    <li class="inline-block no-underline hover:text-black hover:underline py-2 px-4">
                        <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Category\Widget\Link")->setAnchorText("Women")->setIdPath("category/20")->setTemplate("category/widget/link/link_inline.phtml")->toHtml(); ?>
                    </li>
                    <li class="inline-block no-underline hover:text-black hover:underline py-2 px-4">
                        <?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Category\Widget\Link")->setAnchorText("Men")->setIdPath("category/11")->setTemplate("category/widget/link/link_inline.phtml")->toHtml(); ?>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="order-1 md:order-2 w-full sm:w-auto pb-2 sm:pb-0">
            <?= $block->getChildHtml('logo'); ?>
        </div>

        <div class="order-2 md:order-3 flex items-center" id="nav-content">

            <a id="menu-search-icon" class="pl-3 inline-block no-underline hover:text-black" href="#"
               @click.prevent="searchOpen = !searchOpen; $nextTick(function () { $refs.searchInput.select(); });">
                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </a>

            <a id="menu-customer-icon" class="pl-3 inline-block no-underline hover:text-black" href="<?= $block->escapeUrl($block->getUrl('customer/account/index')) ?>">
                <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <circle fill="none" cx="12" cy="7" r="3"></circle>
                    <path d="M12 2C9.243 2 7 4.243 7 7s2.243 5 5 5 5-2.243 5-5S14.757 2 12 2zM12 10c-1.654 0-3-1.346-3-3s1.346-3 3-3 3 1.346 3 3S13.654 10 12 10zM21 21v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h2v-1c0-2.757 2.243-5 5-5h4c2.757 0 5 2.243 5 5v1H21z"></path>
                </svg>
            </a>

            <a id="menu-cart-icon"
               @click.prevent.stop="$dispatch('toggle-cart',{});"
               class="pl-3 inline-block no-underline hover:text-black relative"
               href="<?= $block->escapeUrl($block->getUrl('checkout/cart/index')) ?>">
                <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path d="M21,7H7.462L5.91,3.586C5.748,3.229,5.392,3,5,3H2v2h2.356L9.09,15.414C9.252,15.771,9.608,16,10,16h8 c0.4,0,0.762-0.238,0.919-0.606l3-7c0.133-0.309,0.101-0.663-0.084-0.944C21.649,7.169,21.336,7,21,7z M17.341,14h-6.697L8.371,9 h11.112L17.341,14z"></path>
                    <circle cx="10.5" cy="18.5" r="1.5"></circle>
                    <circle cx="17.5" cy="18.5" r="1.5"></circle>
                </svg>
                <span x-show="cart.summary_count" x-text="cart.summary_count"
                :class="{
                'hidden': !cart.summary_count,
                'absolute top-0 right-0 -mt-4 -mr-4 text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-indigo-600 bg-indigo-200 uppercase': cart.summary_count }"></span>
            </a>

        </div>
    </div>
    <!--Search-->
    <div class="absolute w-full hidden bg-white border" id="search-content"
         :class="{ 'block': searchOpen, 'hidden': !searchOpen }"
         @click.away="searchOpen = false"
         x-show="true">
        <?= $block->getChildHtml('header-search'); ?>

    </div>
    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>
</nav>

