<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Hyva\Theme\ViewModel\StoreConfig $storeConfig */
$storeConfig = $viewModels->require(Hyva\Theme\ViewModel\StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(\Magento\Checkout\Block\Cart\Sidebar::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            },
            get isCartEmpty () {
                return !this.cart.summary_count
            }
        }
    }
    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
    function initCartButton() {
        return {
            showTooltip: false,
            isCartOpen: false
        }
    }
</script>
<div id="header"
     class="relative z-30 w-full border-b shadow bg-container-lighter border-container-lighter"
     x-data="initHeader()"
     @keydown.window.escape="searchOpen = false;"
     @private-content-loaded.window="getData(event.detail.data)"
>
    <div class="container flex flex-wrap items-center justify-between w-full px-6 py-3 mx-auto mt-0">
        <!--Logo-->
        <?= $block->getChildHtml('logo'); ?>

        <!--Main Navigation-->
        <?= $block->getChildHtml('topmenu') ?>

        <div class="flex items-center order-3">
            <!--Compare Icon-->
            <a id="compare-link"
               class="relative invisible inline-block mx-1 no-underline sm:ml-3 hover:text-black"
               :class="{ 'invisible': !(itemCount > 0) }"
               href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
               title="<?= $escaper->escapeHtml(__('Compare Products')) ?>"
               x-data="initCompareHeader()"
               @private-content-loaded.window="receiveCompareData($event.detail.data)"
            >
                <?= $heroicons->scaleHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>

                <span class="sr-only label">
                   <?= $escaper->escapeHtml(__('Compare Products')) ?>
                </span>

                <span class="absolute top-0 right-0 h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                    leading-none text-center text-white uppercase transform -translate-x-1
                    translate-y-1/2 bg-yellow-500 rounded-full"
                >
                    <span x-text="itemCount"></span>
                    <span x-show="itemCount === 1" class="sr-only">
                        <?= $escaper->escapeHtml(__('item')) ?>
                    </span>
                    <span x-show="itemCount > 1" class="sr-only">
                        <?= $escaper->escapeHtml(__('items')) ?>
                    </span>
                </span>
            </a>

            <!--Search Icon-->
            <button id="menu-search-icon"
                    class="inline-block ml-1 no-underline sm:ml-3 hover:text-black"
                    @click.prevent="
                        searchOpen = !searchOpen;
                        $nextTick(() => {
                         const searchInput = document.querySelector('#search');
                         searchInput.focus();
                         searchInput.select();
                     });
                    "
            >
                <span class="sr-only label">
                    <?= $escaper->escapeHtml(__('Search')) ?>
                </span>

                <?= $heroicons->searchHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>
            </button>

            <!--Customer Icon & Dropdown-->
            <?= $block->getChildHtml('customer') ?>

            <!--Cart Icon-->
            <?php if ($showMiniCart): ?>
                <button
            <?php else: ?>
                <a
            <?php endif ?>
                id="menu-cart-icon"
                class="relative inline-block ml-1 no-underline sm:ml-3 hover:text-black"
                x-data="initCartButton()"
                @mouseover.prevent.stop="showTooltip = true"
                @mouseleave.prevent.stop="showTooltip = false"
                @focus.prevent.stop="showTooltip = true"
                @blur.prevent.stop="showTooltip = false"
                :aria-disabled="isCartEmpty"
                <?php if ($showMiniCart): ?>
                    @click.prevent.stop="$dispatch('toggle-cart', { isOpen: true })"
                    @toggle-cart.window="isCartOpen = $event.detail.isOpen"
                    :aria-expanded="isCartOpen"
                    aria-haspopup="dialog"
                <?php else: ?>
                    :href="isCartEmpty ? '#' : '<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>'"
                <?php endif ?>
            >
                <span
                    class="sr-only label"
                    x-text="`
                        <?= $escaper->escapeHtml(__($showMiniCart ? 'Toggle minicart' : 'View cart')) ?>,
                        ${isCartEmpty ?
                        '<?= $escaper->escapeHtml(__('Cart is empty')) ?>' :
                        hyva.str(
                            'You have %1 product%2 in your cart.',
                            cart.summary_count,
                            cart.summary_count === 1 ? '' : 's'
                        )}`
                    "
                >
                </span>

                <span
                    x-cloak
                    x-show="isCartEmpty && showTooltip"
                    x-transition:enter="transition ease-out duration-200"
                    x-transition:enter-start="opacity-0 scale-90"
                    x-transition:enter-end="opacity-100 scale-100"
                    x-transition:leave="transition ease-in duration-200"
                    x-transition:leave-start="opacity-100 scale-100"
                    x-transition:leave-end="opacity-0 scale-90"
                    class="
                        absolute left-1/2 -translate-x-3/4 translate-y-10 p-4 whitespace-nowrap text-sm
                        leading-tight text-black bg-white rounded-lg shadow-t-lg pointer-events-none
                        lg:-translate-x-1/2
                    "
                >
                    <?= $escaper->escapeHtml(__('Cart is empty')) ?>
                    <svg
                        class="
                            absolute top-1.5 left-3/4 z-10 text-white -translate-x-1/2
                            -translate-y-full rotate-[135deg] fill-current lg:left-1/2
                        "
                        width="12"
                        height="12"
                        viewBox="0 0 6 6"
                        focusable="false"
                        aria-hidden="true"
                    >
                        <path d="m0 0 6 6H0Z"/>
                    </svg>
                </span>

                <?= $heroicons->shoppingCartHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>

                <span
                    x-text="cart.summary_count"
                    x-show="!isCartEmpty"
                    class="
                        absolute top-0 right-0 h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                        leading-none text-center text-white uppercase transform -translate-x-1
                        translate-y-1/2 rounded-full bg-primary
                    "
                ></span>
            <?php if ($showMiniCart): ?>
                </button>
            <?php else: ?>
                </a>
            <?php endif ?>

        </div>
    </div>
    <!--Search-->
    <div class="absolute z-10 w-full border-t shadow-sm bg-container-lighter border-container-lighter"
         id="search-content"
         :class="{ 'block': searchOpen}" x-cloak x-show="searchOpen"
         @click.outside="searchOpen = false"
    >
        <?= $block->getChildHtml('header-search'); ?>
    </div>

    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>

