<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

?>

<style>
    @media print {
        .page-print .page-main {
            margin-block: 0 !important;
        }

        .page-print :is(.actions-toolbar, .order-title a) {
            display: none !important;
        }
    }
</style>

<script>
    window.print();
</script>
