<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$target = $block->getTarget();
$label = $block->getLabel();
?>
<a class="action skip sr-only <?= $escaper->escapeHtmlAttr($target) ?> 
          focus:not-sr-only focus:absolute focus:z-40 focus:bg-white"
   href="#<?= $escaper->escapeHtmlAttr($target) ?>">
    <span>
        <?= $escaper->escapeHtml($label) ?>
    </span>
</a>
