<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$headingTag = $block->getData('heading_tag') ?: 'h1';
$textSizeCssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : ' text-3xl';
$titleContainerClasses = $block->getData('maybe_purged_tailwind_section_classes')
    ?? 'container flex flex-col md:flex-row flex-wrap my-6 font-bold lg:mt-8';
$isAriaHidden = $block->getData('aria_hidden') !== null ? (bool) $block->getData('aria_hidden') : false;

$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml): ?>
<div class="<?= $escaper->escapeHtmlAttr($titleContainerClasses . $textSizeCssClass) ?>">
    <<?= /* @noEscape */ $headingTag ?>
        class="text-gray-900 page-title title-font"
        <?php if ($block->getId()): ?>id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>"<?php endif; ?>
        <?php if ($isAriaHidden): ?>aria-hidden="true"<?php endif; ?>
    >
        <?= /* @noEscape */ $titleHtml ?>
    </<?= /* @noEscape */ $headingTag ?>>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
