<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SwatchRenderer;
use Magento\Framework\Escaper;
use Magento\Swatches\Block\Product\Renderer\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

/** @var SwatchRenderer $swatchRendererViewModel */
$swatchRendererViewModel = $viewModels->require(SwatchRenderer::class);

$product = $block->getProduct();
$productId = $product->getId();

$attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($product->isSaleable() && count($attributes)): ?>

    <?= $block->getChildHtml('options_configurable_js') ?>
    <?= $block->getChildHtml('options_swatch_js') ?>

    <script>
        function initConfigurableSwatchOptions_<?= (int) $productId ?>() {
            const configurableOptionsComponent = initConfigurableOptions(
                '<?= (int) $productId ?>',
                <?= /* @noEscape */ $block->getJsonConfig() ?>
            );
            const swatchOptionsComponent = initSwatchOptions(
                <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>
            );

            return Object.assign(
                configurableOptionsComponent,
                swatchOptionsComponent
            );
        }
    </script>

    <div x-data="initConfigurableSwatchOptions_<?= (int) $productId ?>()"
         x-init="findAllowedAttributeOptions();"
         @private-content-loaded.window="onGetCartData($event.detail.data)"
         class="mb-6 relative"
    >
        <h2 class="text-gray-900 text-xl title-font font-medium mb-4">
            <?= $escaper->escapeHtml(__('Product Options:')) ?>
        </h2>
        <div>
            <?php foreach ($attributes as $attribute): ?>
                <?php $attributeId = $attribute->getAttributeId(); ?>
                <?php $productAttribute = $attribute->getProductAttribute();  ?>

                <?php if ($swatchRendererViewModel->isSwatchAttribute($productAttribute)): ?>
                    <div class="swatch-attribute border-t last:border-b border-container
                            <?= $escaper->escapeHtmlAttr($productAttribute->getAttributeCode()) ?>">
                        <div class="flex border-gray-300 py-1 min-h-14 w-full items-center">

                            <label class="label text-gray-700 text-left w-1/2"
                                   for="attribute<?= $escaper->escapeHtmlAttr($productAttribute->getAttributeCode()) ?>"
                            >
                                <span>
                                    <?= $escaper->escapeHtml($productAttribute->getStoreLabel()) ?>
                                </span>
                            </label>
                            <div class="ml-2 text-gray-900 text-left w-1/2">
                                <div
                                     class="flex space-x-4 -mx-4 items-center swatch-attribute-options"
                                     role="radiogroup"
                                     aria-labelledby="radiogroup-label"
                                >
                                    <template
                                        x-for="(item, index) in getAllowedAttributeOptions(<?= (int) $attributeId ?>)"
                                        :key="item.id"
                                    >
                                        <label
                                            :for="'attribute-option-'+item.id"
                                            :class="{
                                                'border-container-lighter ring ring-primary ring-opacity-50':
                                                    (selectedValues[<?= (int)$attributeId ?>] === item.id),
                                                'border-container-darker':
                                                    (selectedValues[<?= (int)$attributeId ?>] !== item.id),
                                                'w-6 h-6' : !isTextSwatch(<?= (int) $attributeId ?>, item.id)
                                             }"
                                            class="swatch-option border-2 cursor-pointer bg-container-lighter shadow-sm select-none"
                                            :style="getSwatchBackgroundStyle('<?= (int) $attributeId ?>',item.id)"
                                            <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
                                                @mouseenter.self="activeTooltipItem = {
                                                attribute: '<?= (int) $attributeId ?>',
                                                item: item.id
                                            }; tooltipPositionElement = $event.target;"
                                                @mouseleave.self="activeTooltipItem = false"
                                            <?php endif; ?>
                                        >
                                            <input
                                                :id="'attribute-option-'+item.id"
                                                :value="item.id"
                                                name="super_attribute[<?= (int) $attributeId ?>]"
                                                type="radio"
                                                class="border-0 focus:border-0 focus:ring-0 absolute inline-block p-0"
                                                style="z-index:-1"
                                                x-on:change="changeOption(<?= (int) $attributeId ?>, event.target.value)"
                                                :checked="selectedValues[<?= (int) $attributeId ?>] === item.id"
                                                :required="getAllowedAttributeOptions(<?= (int) $attributeId ?>).filter(
                                                        attributeOption => selectedValues[attributeOption]
                                                    ).length === 0"
                                            >
                                            <div x-html="getSwatchText(<?= (int) $attributeId ?>, item.id)"
                                                 class="whitespace-nowrap"
                                                 :class="{ 'sr-only' : !isTextSwatch(<?= (int) $attributeId ?>, item.id) }"
                                            ></div>
                                        </label>
                                    </template>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="flex border-t last:border-b  border-gray-300 py-2 w-full items-center">
                        <label class="label text-gray-700 text-left w-1/2"
                               for="attribute<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>"
                        >
                            <span>
                                <?= $escaper->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?>
                            </span>
                        </label>
                        <div class="ml-2 text-gray-900 text-left w-1/2">
                            <select name="super_attribute[<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>]"
                                    id="attribute<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>"
                                    class="form-select super-attribute-select"
                                    x-on:change="changeOption(<?= (int) $attribute->getAttributeId() ?>, event.target.value)"
                                    required="required">
                                <option value="">
                                    <?= $escaper->escapeHtml(__('Choose an Option...')) ?>
                                </option>
                                <template
                                    x-for="(item, index) in getAllowedAttributeOptions(<?= (int) $attribute->getAttributeId() ?>)"
                                    :key="item.id"
                                >
                                    <option
                                        :value="item.id"
                                        x-html="item.label"
                                        :selected="selectedValues[<?= $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>] ===
                                item.id">
                                    </option>
                                </template>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

        <?php if ($swatchRendererViewModel->isSwatchAttribute($productAttribute)): ?>
            <template x-if="activeTooltipItem && getSwatchConfig(activeTooltipItem.attribute, activeTooltipItem.item)">
                <div class="absolute"
                     :style="getTooltipPosition()"
                >
                    <div class="shadow-lg">
                        <div class="absolute top-0 left-0 z-10 min-w-20 p-2 -mt-6 text-sm leading-tight text-black
                                transform -translate-x-1/2 -translate-y-full bg-white rounded-lg shadow-lg text-center"
                        >
                        <template x-if="isVisualSwatch(activeTooltipItem.attribute, activeTooltipItem.item)">
                            <div class="inline-block border border-container shadow-sm"
                                 :style="getTooltipImageStyle(activeTooltipItem.attribute, activeTooltipItem.item)"
                            ></div>
                        </template>
                            <span class="subtitle text-lg font-semibold whitespace-nowrap mx-2"
                                  x-html="getSwatchConfig(activeTooltipItem.attribute, activeTooltipItem.item).label"
                            ></span>
                        </div>
                        <svg class="absolute z-10 w-8 h-8 text-white transform -translate-x-1/5
                                -translate-y-8 fill-current stroke-current"
                             width="12"
                             height="12"
                        >
                            <rect x="12" y="-12" width="12" height="12" transform="rotate(45)" class="shadow-xl" />
                        </svg>
                    </div>
                </div>
            </template>
        <?php endif; ?>
    </div>

<?php endif;?>

