<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            totalCartAmount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.totalCartAmount = this.cart.summary_count;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('(%0 <?= $escaper->escapeJs(__('of')) ?> %1)', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;
                fetch(`${BASE_URL}checkout/sidebar/removeItem/`, {
                    headers: {
                        contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    },
                    body: "form_key=" + hyva.getFormKey() + "&item_id=" + itemId,
                    method: 'POST',
                    mode: 'cors',
                    credentials: 'include'
                }).then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            }
        }
    }
</script>
<section id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="open=true"
         @keydown.window.escape="open=false"
>
    <template x-if="cart && cart.summary_count">
        <div role="dialog"
             aria-labelledby="cart-drawer-title"
             aria-modal="true"
             @click.away="open=false"
             class="fixed inset-y-0 right-0 z-30 flex max-w-full">
            <div class="backdrop"
                 x-show="open"
                 x-transition:enter="ease-in-out duration-500"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in-out duration-500"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
                 @click="open=false"
                 aria-label="Close panel"></div>
            <div class="relative w-screen max-w-md shadow-2xl"
                 x-show="open"
                 x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:enter-start="translate-x-full"
                 x-transition:enter-end="translate-x-0"
                 x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:leave-start="translate-x-0"
                 x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 flex p-2 mt-2">
                    <button @click="open=false" aria-label="Close panel"
                            class="p-2 text-gray-300 transition duration-150 ease-in-out hover:text-black">
                        <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                  stroke-width="2" d="M6 18L18 6M6 6l12 12">
                            </path>
                        </svg>
                    </button>
                </div>
                <div class="flex flex-col h-full py-6 space-y-6 bg-white shadow-xl">
                    <header class="px-4 sm:px-6">
                        <h2 id="cart-drawer-title" class="text-lg font-medium leading-7 text-gray-900">
                            <?= $escaper->escapeHtml(__('My Cart')) ?>
                            <span class="items-total text-xs"
                                  x-show="maxItemsToDisplay && maxItemsToDisplay < itemsCount"
                                  x-text="getItemCountTitle()">
                            </span>
                        </h2>
                    </header>
                    <div class="relative grid gap-6 px-4 py-6 overflow-y-auto bg-white border-b
                        sm:gap-8 sm:px-6 border-container">
                        <template x-for="item in cartItems">
                            <div class="flex items-start p-3 -m-3 space-x-4 transition duration-150
                                ease-in-out rounded-lg hover:bg-gray-100">
                                <a :href="item.product_url" class="w-1/4">
                                    <img
                                        :src="item.product_image.src"
                                        :width="item.product_image.width"
                                        :height="item.product_image.height"
                                        loading="lazy"
                                    />
                                </a>
                                <div class="w-3/4 space-y-2">
                                    <div>
                                        <p class="text-xl">
                                            <span x-html="item.qty"></span> x <span x-html="item.product_name"></span>
                                        </p>
                                        <p class="text-sm"><span x-html="item.product_sku"></p>
                                    </div>
                                    <template x-for="option in item.options">
                                        <div class="pt-2">
                                            <p class="font-semibold" x-text="option.label + ':'"></p>
                                            <p class="text-secondary" x-html="option.value"></p>
                                        </div>
                                    </template>
                                    <p><span x-html="item.product_price"></span></p>
                                    <div class="pt-4">
                                        <a :href="item.configure_url"
                                           x-show="item.product_type !== 'grouped'"
                                           class="inline-flex p-2 mr-2 btn btn-primary">
                                            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor"
                                                 size="16" class="w-5 h-5">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                      d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536
                                                      3.536L6.5 21.036H3v-3.572L16.732 3.732z">
                                                </path>
                                            </svg>
                                        </a>
                                        <button class="inline-flex p-2 btn btn-primary"
                                            @click="deleteItemFromCart(item.item_id)"
                                        >
                                            <svg fill="none" viewBox="0 0 24 24" stroke="currentColor"
                                                 size="16" class="w-5 h-5">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                      d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0
                                                      01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1
                                                      0 00-1 1v3M4 7h16">
                                                </path>
                                            </svg>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </template>
                    </div>
                    <div class="relative grid gap-6 px-4 py-6 bg-white sm:gap-8 sm:px-6">
                        <div class="w-full p-3 -m-3 space-x-4 transition duration-150 ease-in-out rounded-lg
                            hover:bg-gray-100">
                            <p><?= $escaper->escapeHtml(__('Subtotal')) ?>: <span x-html="cart.subtotal"></span></p>
                        </div>
                        <div class="w-full p-3 -m-3 space-x-4 transition duration-150 ease-in-out
                            rounded-lg hover:bg-gray-100">
                            <a @click.prevent.stop="$dispatch('toggle-authentication',
                                {url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'});"
                                href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                                class="inline-flex btn btn-primary">
                                <?= $escaper->escapeHtml(__('Checkout')) ?>
                            </a>
                            <span><?= $escaper->escapeHtml(__('or')) ?></span>
                            <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                               class="underline">
                                <?= $escaper->escapeHtml(__('View and Edit Cart')) ?>
                            </a>
                        </div>
                        <?= $block->getChildHtml('extra_actions') ?>
                    </div>
                </div>
            </div>
            <?= $block->getChildHtml('loading') ?>
        </div>
    </template>
</section>
