<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Customer\Block\Widget\Dob;
use Magento\Customer\ViewModel\Address as AddressViewModel;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Dob $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroIconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var AddressViewModel $addressViewModel */
$addressViewModel = $viewModels->require(AddressViewModel::class);

$validationClass = $addressViewModel->addressGetAttributeValidationClass('dob');
?>
<div
    class="field date customer-dob <?= $block->isRequired() ? 'required' : '' ?>"
    x-data="initDatePicker()"
>
    <label for="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>_picker" class="label">
        <span><?= $escaper->escapeHtml($block->getStoreLabel('dob')) ?></span>
    </label>
    <div class="control">
        <input
            type="date"
            id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>_picker"
            name="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>_picker"
            class="form-input <?= $escaper->escapeHtmlAttr($validationClass) ?: '' ?>"
            placeholder="<?= $escaper->escapeHtml($block->getDateFormat()) ?>"
            autocomplete="off"
            x-model="valuePicker"
            :min="minDateValue"
            :max="maxDateValue"
        >
        <input
            type="hidden"
            name="<?= $escaper->escapeHtmlAttr($block->getFieldName('dob')) ?>"
            x-model="value"
            <?php if ($block->isRequired()): ?>
                required
            <?php endif; ?>
        >
        <ul>
            <li></li>
        </ul>
    </div>
</div>
<script>
    function initDatePicker() {
        const format = '<?= $escaper->escapeHtml($block->getDateFormat()) ?>';

        return {
            value: '<?= $escaper->escapeHtml($block->getValue()) ?>',
            valuePicker: null,
            init() {
                this.valuePicker = this.convertDateToUTC(this.value) || new Date().toISOString().substr(0, 10);
                this.$watch('valuePicker', value => {
                    this.value = this.convertDateToLocale(value);
                });
            },
            maxDateValue() {
                return this.dateToInputDate(new Date());
            },
            minDateValue() {
                const today = new Date();
                const utcDate = new Date(Date.UTC(today.getUTCFullYear() - 120, today.getMonth(), today.getDate()));
                return this.dateToInputDate(utcDate);
            },
            dateToInputDate(date) {
                const year = date.getFullYear();
                const month = date.getMonth() + 1;
                const day = date.getDate();
                return `${year.toString().padStart(4, '0')}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
            },
            convertDateToUTC(value) {
                try {
                    const dateObj = new Date(value);
                    const utcDate = new Date(Date.UTC(dateObj.getFullYear(), dateObj.getMonth(), dateObj.getDate()));
                    return this.dateToInputDate(utcDate);
                } catch (err) {
                    return null;
                }
            },
            convertDateToLocale(value) {
                try {
                    const date = new Date(value);
                    return new Intl.DateTimeFormat('en-US').format(date);
                } catch (err) {
                    return '';
                }
            }
        }
    }
</script>
