<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @load.window="setActiveMenu($root)"
    @keydown.window.escape="closeMenu()"
    class="z-20 order-2 sm:order-1 lg:order-2 navigation lg:hidden h-12"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
>
    <!-- mobile -->
    <button
        @click="openMenu()"
        :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open"
    >
        <?= $heroicons->menuHtml(
            'p-3', 48, 48,
            [":class" => "{ 'hidden' : open, 'block': !open }", "role" => "presentation", "focusable" => "false"]
        );?>
    </button>
    <div
        class="fixed top-0 right-0 w-full h-full p-1 flex flex-col
            duration-150 ease-in-out transform  transition-display border-t
            border-container z-21  bg-container-lighter
        "
        :class="{ 'hidden' : !open }"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true"
    >
        <ul
            class="border-t flex flex-col gap-y-1 mt-[68px]"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <li class="level-0">
                    <div
                        class="flex items-center transition-transform duration-150 ease-in-out transform"
                        :class="{
                            '-translate-x-full' : mobilePanelActiveId,
                            'translate-x-0' : !mobilePanelActiveId
                        }"
                    >
                        <a
                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-container-lighter border-container level-0
                            "
                            href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                            title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                            tabindex="0"
                        >
                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                        </a>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <button
                                @click="mobilePanelActiveId = mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'
                                    ? 0
                                    : '<?= /* @noEscape */ (string) $index ?>'
                                "
                                class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                bg-container-lighter border-container"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Open')) ?><?= $escaper->escapeHtmlAttr($menuItem['name']) ?><?= $escaper->escapeHtmlAttr(__('subcategories')) ?>"
                            >
                                <div class="w-8 h-8 border rounded">
                                    <?= $heroicons->chevronRightHtml(
                                        'w-full h-full p-1', 24, 24,
                                        ["role" => "presentation", "focusable" => "false"]
                                    ); ?>
                                </div>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            x-ref="<?= /* @noEscape */ (string) $index ?>"
                            x-init="trapFocus($refs['<?= /* @noEscape */ (string) $index ?>'])"
                            class="absolute top-0 right-0 z-10 flex flex-col gap-1 w-full h-full p-1 bg-container-lighter"
                            :class="{
                                'invisible': mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>'
                            }"
                        >
                            <ul
                                class="mt-[68px] transition-transform duration-200 ease-in-out translate-x-full transform"
                                :class="{
                                    'translate-x-full' : mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                    'translate-x-0' : mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>',
                                }"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
                            >
                                <li>
                                    <button
                                        class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container w-full border-t"
                                        @click="mobilePanelActiveId = 0"
                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main categories')) ?>"
                                    >
                                        <?= $heroicons->chevronLeftHtml('', 24, 24, ["role" => "presentation", "focusable" => "false"]); ?>
                                        <span class="ml-4">
                                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                                        </span>
                                    </button>
                                </li>
                                <li>
                                    <a
                                        href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                        title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                            bg-container-lighter border-container
                                        "
                                    >
                                        <span class="ml-10">
                                            <?= $escaper->escapeHtml(__('View All')) ?>
                                        </span>
                                    </a>
                                </li>
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li>
                                        <a
                                            href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                            title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                bg-container-lighter border-container
                                            "
                                        >
                                            <span class="ml-10 text-base text-gray-700">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <button
                                @click="closeMenu()"
                                class="absolute flex justify-end w-16 self-end mb-1 transition-none"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                            >
                                <?= $heroicons->xHtml(
                                    'hidden p-4', 64, 64,
                                    [":class" => "{ 'hidden' : !open, 'block': open }", "role" => "presentation", "focusable" => "false"]
                                ); ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <button
            @click="closeMenu()"
            class="absolute flex justify-end w-16 self-end mb-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button"
        >
            <?= $heroicons->xHtml(
                'hidden p-4', 64, 64,
                [":class" => "{ 'hidden' : !open, 'block': open }", "role" => "presentation", "focusable" => "false"]
            ); ?>
        </button>
    </div>
</nav>
<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('li.level-0') &&
                    item.closest('li.level-0').querySelector('a.level-0').classList.add('underline');
                });

                this.trapFocus(menuNode)
            },
            trapFocus(menuNode) {
                const focusableElements = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';
                const focusableContentWithoutTrigger = Array.from(menuNode.querySelectorAll(focusableElements))
                    .filter(el => el.getAttribute('aria-haspopup') !== 'menu')

                const firstFocusableElement = focusableContentWithoutTrigger.length > 0
                    ? focusableContentWithoutTrigger[0]
                    : null;
                const lastFocusableElement = focusableContentWithoutTrigger.length > 0
                    ? focusableContentWithoutTrigger[focusableContentWithoutTrigger.length - 1]
                    : null;

                document.addEventListener('keydown', function(e) {
                    const isTabPressed = e.key === 'Tab' || e.keyCode === 9;

                    if (!isTabPressed) {
                        return;
                    }

                    e.shiftKey
                        ? document.activeElement === firstFocusableElement && (lastFocusableElement.focus(), e.preventDefault())
                        : document.activeElement === lastFocusableElement && (firstFocusableElement.focus(), e.preventDefault());
                });
            },
            openMenu() {
                this.open = true

                // Prevent from body scrolling while mobile menu opened
                document.body.style.position = 'fixed';
            },
            closeMenu() {
                document.body.style.position = '';
                this.open = false
                this.mobilePanelActiveId = null
            }
        }
    }
</script>
