<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;

/** @var $escaper Escaper */
/** @var $block Magento\Framework\View\Element\Template */
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            cart: {},
            getCart: function (data) {
                if (data.cart) {
                    this.cart = data.cart
                }
            }
        }
    }
</script>
<section id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getCart(event.detail.data)"
         @toggle-cart.window="open=true;"
         @keydown.window.escape="open=false"
>
    <template x-if="cart && cart.summary_count">
        <div role="dialog"
             aria-labelledby="cart-drawer-title"
             aria-modal="true"
             @click.away="open = false"
             class="fixed inset-y-0 right-0 max-w-full flex z-30">
            <div class="relative w-screen max-w-md"
                 x-show="open"
                 x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:enter-start="translate-x-full"
                 x-transition:enter-end="translate-x-0"
                 x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:leave-start="translate-x-0"
                 x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 mt-2 p-2 flex">
                    <button @click="open = false;" aria-label="Close panel"
                            class="text-gray-300 hover:text-black transition ease-in-out duration-150 p-2">
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M6 18L18 6M6 6l12 12"></path>
                        </svg>
                    </button>
                </div>
                <div class="h-full flex flex-col space-y-6 py-6 bg-white shadow-xl">
                    <header class="px-4 sm:px-6">
                        <h2 id="cart-drawer-title" class="text-lg leading-7 font-medium text-gray-900">
                            <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                               class="underline"><?= $escaper->escapeHtml(__('My Cart')) ?></a>
                        </h2>
                    </header>
                    <div class="relative grid gap-6 bg-white py-6 sm:gap-8 px-4 sm:px-6">
                        <template x-for="item in cart.items">
                            <div
                                class="-m-3 p-3 flex items-start space-x-4 rounded-lg hover:bg-gray-100 transition ease-in-out duration-150">
                                <a :href="item.product_url">
                                    <img
                                        :src="item.product_image.src"
                                        :width="item.product_image.width"
                                        :height="item.product_image.height"
                                        loading="lazy"
                                    />
                                </a>
                                <div class="space-y-1">
                                    <p><span x-html="item.qty"></span> x <span x-html="item.product_name"></span></p>
                                    <p><span x-html="item.product_price"></span></p>
                                    <p><a :href="item.configure_url">edit</a></p>
                                </div>
                            </div>
                        </template>
                    </div>
                    <div class="relative grid gap-6 bg-white py-6 sm:gap-8 px-4 sm:px-6">
                        <div
                            class="w-full -m-3 p-3 space-x-4 rounded-lg hover:bg-gray-100 transition ease-in-out duration-150">
                            <p>Subtotal: <span x-html="cart.subtotal"></span></p>
                        </div>
                        <div
                            class="w-full -m-3 p-3 space-x-4 rounded-lg hover:bg-gray-100 transition ease-in-out duration-150">
                            <a href="<?= $block->getUrl('checkout/index') ?>" class="btn btn-primary">Checkout</a>
                            <span>or</span> <a href="<?= $block->getUrl('checkout/cart') ?>" class="underline">Go to
                                Cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </template>
</section>
