<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Catalog\Block\Category\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $block->getImage()->getUrl($_category)) {
        $_imgHtml = '<div class="category-image"><img src="'
            . $escaper->escapeUrl($_imgUrl)
            . '" alt="'
            . $escaper->escapeHtmlAttr($_category->getName())
            . '" title="'
            . $escaper->escapeHtmlAttr($_category->getName())
            . '" class="image" /></div>';
        $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
        /* @noEscape */ echo $_imgHtml;
    }
?>
