<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Catalog\Block\Category\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */

?>
<?php
$category = $block->getCurrentCategory();
$imgHtml  = '';
if ($imgUrl = $block->getImage()->getUrl($category)) {
    $imgHtml = '<div class="category-image"><img src="'
        . $escaper->escapeUrl($imgUrl)
        . '" alt="'
        . $escaper->escapeHtmlAttr($category->getName())
        . '" title="'
        . $escaper->escapeHtmlAttr($category->getName())
        . '" class="image" /></div>';
    /* @noEscape */ echo $block->getOutput()->categoryAttribute($category, $imgHtml, 'image');
}
?>
