<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use \Magento\Catalog\Block\Category\View;

/** @var View $block */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
    <?= $block->getProductListHtml() ?>
<?php else: ?>
    <?= $block->getChildHtml('cms.block.main') ?>
<?php endif; ?>
