<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

$order = $block->getOrder() ?>
<?php foreach ($order->getCreditmemosCollection() as $creditmemo) : ?>
    <div class="order-title text-center md:text-left font-semibold">
        <?= $block->escapeHtml(__('Refund #')) ?><?= $block->escapeHtml(
                $creditmemo->getIncrementId()
            ) ?>
        <a href="<?= $block->escapeUrl($block->getPrintCreditmemoUrl($creditmemo)) ?>"
           class="text-primary inline-block ml-2 pl-2 border-l text-sm font-normal"
            target="_blank"
            rel="noopener">
            <svg class="inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                 width="20" height="20">
                <path fill-rule="evenodd"
                      d="M5 4v3H4a2 2 0 00-2 2v3a2 2 0 002 2h1v2a2 2 0 002 2h6a2 2 0 002-2v-2h1a2 2 0 002-2V9a2 2 0 00-2-2h-1V4a2 2 0 00-2-2H7a2 2 0 00-2 2zm8 0H7v3h6V4zm0 8H7v4h6v-4z"
                      clip-rule="evenodd"/>
            </svg>
            <span class="inline-block ml-1 underline"><?= $block->escapeHtml(__('Print Refund')) ?></span>
        </a>
    </div>

    <?= $block->getCommentsHtml($creditmemo) ?>

    <div class="order-items creditmemo">
        <div class="hidden lg:grid grid-cols-7 text-sm text-secondary ">
            <div class="p-2 col-span-2"><?= $escaper->escapeHtml(__('Product Name')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Price')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Qty')) ?></div>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Subtotal')) ?></div>
            <div class="p-2 text-right"><?= $block->escapeHtml(__('Discount Amount')) ?></div>
            <div class="p-2 text-right"><?= $block->escapeHtml(__('Row Total')) ?></div>
        </div>
        <?php $items = $creditmemo->getAllItems(); ?>
        <?php foreach ($items as $item) : ?>
            <?php if (!$item->getOrderItem()->getParentItem()) : ?>
                <?= $block->getItemHtml($item) ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="flex justify-end border-t border-container">
            <div class="lg:w-1/3">
                <div class="grid grid-cols-2 text-right p-2 gap-2">
                    <?= $block->getTotalsHtml($creditmemo) ?>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
