<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

/** @var Escaper $escaper */
/** @var Template $block */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$label = $block->getData('label') ?? __('My Wish List');
$urlPath = $block->getData('path') ?? 'wishlist';

?>
<a id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
   class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative"
   href="<?= $escaper->escapeUrl($block->getUrl($urlPath)) ?>"
   title="<?= $escaper->escapeHtmlAttr($label) ?>"
   x-data="{itemCount: 0}"
   @private-content-loaded.window="itemCount = parseInt($event.detail.data.wishlist.counter)"
>
    <span class="flex items-center">
        <?= $escaper->escapeHtml($label) ?>
        <template x-if="itemCount">
            <span class="h-5 px-2 py-1 ml-2 -mt-0.5 text-xs font-semibold leading-none text-center text-white uppercase bg-yellow-500 rounded-full">
                <span x-text="itemCount"></span>
            </span>
        </template>
    </span>
</a>
