<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Recent;
use Magento\Sales\Helper\Reorder;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Recent $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$orders = $block->getOrders();
$count  = count($orders);
?>
<div class="block block-dashboard-orders card mt-4"
     x-data="{ tabIndex: -1 }"
>
    <div class="block-title order my-4 flex justify-between items-center">
        <h2 id="recentOrders"
            class="text-2xl block"
            @focus="tabIndex = 0;"
            @blur="tabIndex = -1"
            :tabindex="tabIndex"
        >
          <?= $escaper->escapeHtml(__('Recent Orders')) ?>
        </h2>
        <?php if ($count > 0): ?>
            <a
                class="action view inline-block underline"
                href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
                aria-label="<?= $escaper->escapeHtmlAttr(__('View all orders')) ?>"
            >
                <?= $escaper->escapeHtml(__('View All')) ?>
            </a>
        <?php endif; ?>
    </div>
    <div
        role="table"
        class="block-content"
        aria-labelledby="recentOrders"
    >
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0): ?>
            <div
                role="row"
                id="my-orders-table"
                class="grid grid-cols-3 lg:grid-cols-6"
            >
                <div
                    role="columnheader"
                    class="text-sm text-secondary p-2"
                >
                    <?= $escaper->escapeHtml(__('Order #')) ?>
                </div>
                <div
                    role="columnheader"
                    class="text-sm hidden lg:block text-secondary p-2"
                >
                    <?= $escaper->escapeHtml(__('Date')) ?>
                </div>
                <div
                    role="columnheader"
                    class="text-sm text-secondary p-2"
                >
                    <?= $escaper->escapeHtml(__('Ship To')) ?>
                </div>
                <div
                    role="columnheader"
                    class="text-sm hidden lg:block text-secondary p-2"
                >
                    <?= $escaper->escapeHtml(__('Order Total')) ?>
                </div>
                <div
                    role="columnheader"
                    class="text-sm hidden lg:block text-secondary p-2"
                >
                    <?= $escaper->escapeHtml(__('Status')) ?>
                </div>
                <div
                    role="columnheader"
                    class="text-sm text-secondary p-2 text-center"
                >
                    <?= $escaper->escapeHtml(__('View')) ?>
                    <?php if ($this->helper(Reorder::class)->isAllow()): ?>
                        / <?= $escaper->escapeHtml(__('Reorder')) ?>
                    <?php endif; ?>
                </div>
            </div>
            <?php $i = 0; ?>
            <?php foreach ($orders as $order): ?>
                <div
                    role="row"
                    class="grid grid-cols-3 lg:grid-cols-6"
                >
                    <?php $i++; ?>
                    <div
                        id="order<?= $escaper->escapeHtmlAttr($order->getRealOrderId()) ?>"
                        role="rowheader"
                        class="p-2 flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <?= $escaper->escapeHtml($order->getRealOrderId()) ?>
                        <p class="lg:hidden text-sm">
                            <?= $escaper->escapeHtml($block->formatDate($order->getCreatedAt())) ?>
                        </p>
                    </div>
                    <div
                        role="cell"
                        class="p-2 hidden lg:flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <?php
                            $date = $order->getCreatedAt();
                            $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
                            $formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
                        ?>
                        <span aria-hidden="true">
                            <?= $escaper->escapeHtmlAttr($block->formatDate($date, $format)); ?>
                        </span>
                        <span class="sr-only">
                            <?= $escaper->escapeHtml($block->formatDate($date, $formatLong)); ?>
                        </span>
                    </div>
                    <div
                        role="cell"
                        class="p-2 flex items-center<?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <?php if ($order->getBillingAddress() && $order->getBillingAddress()->getCompany()): ?>
                            <?= $escaper->escapeHtml($order->getBillingAddress()->getCompany()) ?>
                        <?php endif; ?>
                    </div>
                    <div
                        role="cell"
                        class="p-2 hidden lg:flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <?= /* @noEscape */ $order->formatPrice($order->getGrandTotal()) ?>
                    </div>
                    <div
                        role="cell"
                        class="p-2 hidden lg:flex items-center <?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <?= $escaper->escapeHtml(
                            $order->getStatusLabel()
                        ) ?>
                    </div>
                    <div
                        role="cell"
                        class="p-2 flex items-center justify-evenly<?= $i % 2 === 0 ? '' : ' bg-container-darker' ?>"
                    >
                        <a
                            href="<?= $escaper->escapeUrl($block->getViewUrl($order)) ?>"
                            class="inline-block text-sm underline text-secondary-darker"
                            title="<?= $escaper->escapeHtmlAttr(__('View Order')) ?>"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                        >
                            <?= $heroicons->eyeHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                        </a>
                        <?php if ($this->helper(Reorder::class)->canReorder($order->getEntityId())): ?>
                            <?php $formData = json_decode(
                                $this->helper(PostHelper::class)->getPostData(
                                    $block->getReorderUrl($order)
                                ),
                                true
                            ) ?>
                            <form action="<?= $escaper->escapeUrl($formData['action']) ?>"
                                  method="post" class="inline-flex items-center">
                                <?= $block->getBlockHtml('formkey'); ?>
                                <input type="hidden" name="data"
                                       value='<?= /* @noEscape */ json_encode($formData['data']) ?>'
                                />
                                <button
                                    title="<?= $escaper->escapeHtmlAttr(__('Reorder')) ?>"
                                    type="submit"
                                    class="inline-block text-sm text-secondary-darker"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Reorder') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                                >
                                    <?= $heroicons->refreshHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                                </button>
                            </form>
                        <?php endif ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have placed no orders.')) ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
