<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @var \Magento\Sales\Block\Order\Totals $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?= $block->getChildHtml($total->getBlockName(), false) ?>
    <?php else:?>
        <div<?= /* @noEscape */ $block->getLabelProperties() ?>>
            <?php if ($total->getStrong()): ?>
                <strong><?= $escaper->escapeHtml($total->getLabel()) ?></strong>
            <?php else: ?>
                <?= $escaper->escapeHtml($total->getLabel()) ?>
            <?php endif ?>
        </div>
        <div <?= /* @noEscape */ $block->getValueProperties() ?>
             data-th="<?= $escaper->escapeHtmlAttr($total->getLabel()) ?>">
            <?php if ($total->getStrong()): ?>
                <strong><?= /* @noEscape */ $block->formatValue($total) ?></strong>
            <?php else: ?>
                <?= /* @noEscape */ $block->formatValue($total) ?>
            <?php endif?>
        </div>
    <?php endif; ?>
<?php endforeach?>
