<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/** @var  $block \Magento\Sales\Block\Order\View*/
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $order = $block->getOrder() ?>
<div class="text-2xl mb-3"><?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></div>
<div class="order-details-items ordered">

    <div class="mb-6">
    <?= $block->getChildHtml('order_top_items') ?>
    </div>

    <?= $block->getChildHtml('sales.order.info') ?>

    <div class="order-title">
        <p class="text-lg mt-8 mb-2"><?= $escaper->escapeHtml(__('Items Ordered')) ?></p>
        <?php if (!empty($order->getTracksCollection()->getItems())) : ?>
            <?= $block->getChildHtml('tracking-info-link') ?>
        <?php endif; ?>
    </div>

    <?= $block->getChildHtml('order_items') ?>

    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order', $order)
        && $order->getGiftMessageId()
    ) : ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?= $escaper->escapeHtml(__('Gift Message for This Order')) ?></strong></div>
        <?php
        $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($order);
        ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?= $escaper->escapeHtml(__('From')) ?></strong><?= $escaper->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?= $escaper->escapeHtml(__('To')) ?></strong><?= $escaper->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message">
                    <?= /* @noEscape */
                    $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($order) ?>
                </dd>
            </dl>
        </div>
    </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <?= $block->getChildHtml('sales.order.info.buttons') ?>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
