<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */use Magento\Customer\Block\Address\Edit;
use Magento\Customer\ViewModel\Address;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Edit $block *//** @var Address $viewModel *//** @var Escaper $escaper *//** @var SecureHtmlRenderer $secureRenderer */$viewModel = $block->getViewModel();
?>
<?php $company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php $country_id = $block->getAttributeData()->getFrontendLabel('country_id'); ?>
<?php $street = $block->getAttributeData()->getFrontendLabel('street'); ?>
<?php $city = $block->getAttributeData()->getFrontendLabel('city'); ?>
<?php $region = $block->getAttributeData()->getFrontendLabel('region'); ?>
<?php $selectRegion = 'Please select a region, state or province.'; ?>
<?php $displayAll = $block->getConfig('general/region/display_all'); ?>

<div class="text-2xl mb-6">
    <?= $escaper->escapeHtml(__('Customer Address')) ?>
</div>
<form class="form-address-edit"
      action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Contact Information')) ?></span></legend>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">

        <div class="md:grid grid-cols-2 gap-x-4 gap-y-0">
            <?= $block->getNameBlockHtml() ?>

            <?php if ($company->isEnabled()): ?>
                <div class="field w-full">
                    <?= $company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
                </div>
            <?php endif ?>

            <?php if ($telephone->isEnabled()): ?>
                <div class="field w-full">
                    <?= $telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
                </div>
            <?php endif ?>

            <?php if ($fax->isEnabled()): ?>
                <div class="field w-full">
                    <?= $fax->setFax($block->getAddress()->getFax())->toHtml() ?>
                </div>
            <?php endif ?>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend w-full"><span><?= $escaper->escapeHtml(__('Address')) ?></span></legend>
        <div class="md:grid grid-cols-2 gap-x-4 gap-y-0">
            <div class="field street w-full">
                <label for="street_1" class="label">
                    <span>
                        <?= /* @noEscape */ $street ?>
                    </span>
                </label>
                <div class="control">
                    <input type="text"
                           name="street[]"
                           required
                           value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                           title="<?= /* @noEscape */ $street ?>"
                           id="street_1"
                    />
                    <div class="nested">
                        <?php for ($i = 1, $n = $viewModel->addressGetStreetLines(); $i < $n; $i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */$i + 1 ?>">
                                    <span><?= $escaper->escapeHtml(__('Street Address %1', $i + 1)) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]"
                                           value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($i + 1)) ?>"
                                           title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $i + 1)) ?>"
                                           id="street_<?= /* @noEscape */ $i + 1 ?>"
                                           class="form-input"
                                    >
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
                <div class="field taxvat w-full">
                    <label class="label" for="vat_id">
                    <span><?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('vat_id') ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="vat_id"
                               value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                               title="<?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('vat_id') ?>"
                               class="form-input"
                               id="vat_id">
                    </div>
                </div>
            <?php endif; ?>
            <div class="field zip w-full">
                <label class="label" for="zip">
                    <span>
                        <?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('postcode') ?>
                    </span>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                           title="<?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           id="zip"
                           required
                           class="form-input validate-zip-international">
                    <input type="hidden"
                           id="region"
                           name="region"
                           value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                           title="<?= /* @noEscape */$region ?>"
                           class="form-input validate-not-number-first"
                        <?= !$displayAll ? ' disabled="disabled"' : '' ?>/>
                </div>
            </div>

            <div class="field city w-full">
                <label class="label" for="city">
                <span><?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('city') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           required
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                           class="form-input"
                           id="city">
                </div>
            </div>

            <div class="field country w-full">
                <label class="label" for="country">
                    <span>
                        <?= /* @noEscape */$block->getAttributeData()->getFrontendLabel('country_id') ?>
                    </span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing">
                    <span><?= $escaper->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= $escaper->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $escaper->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
