<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block block-dashboard-addresses">
    <div class="block-title my-6 flex justify-between items-center">
        <span class="text-2xl block"><?= $escaper->escapeHtml(__('Address Book')) ?></span>
        <a class="action edit inline-block underline"
           href="<?= $escaper->escapeUrl($block->getAddressBookUrl()) ?>"><span><?= $escaper->escapeHtml(
                    __('Manage Addresses')
                ) ?></span></a>
    </div>
    <div class="block-content">
        <div class="flex flex-wrap justify-between -m-4">
            <div class="lg:w-1/2 w-full p-4">
                <div class="flex p-8 sm:flex-row border border-gray-200 flex-col h-full">
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                        </h2>
                        <address>
                            <?= $block->getPrimaryBillingAddressHtml() ?>
                        </address>
                        <a
                            class="mt-3 w-full inline-flex items-center md:text-sm text-secondary hover:text-secondary-darker"
                            href="<?= $escaper->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"><span><?= $escaper->escapeHtml(
                                    __('Edit Address')
                                ) ?></span>
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                 stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <div class="lg:w-1/2 w-full p-4">
                <div class="flex p-8 sm:flex-row border border-gray-200 flex-col h-full">
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                            <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                        </h2>
                        <address>
                            <?= $block->getPrimaryShippingAddressHtml() ?>
                        </address>
                        <a
                            class="mt-3 w-full inline-flex items-center md:text-sm text-secondary hover:text-secondary-darker"
                            href="<?= $escaper->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"><span><?= $escaper->escapeHtml(
                                    __('Edit Address')
                                ) ?></span>
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                 stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
