<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Checkout\Block\Onepage\Success;
use Magento\Framework\Escaper;

/** @var Success $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()): ?>
    <a href="<?= $escaper->escapeUrl($block->getPrintUrl()) ?>"
       class="mt-3 md:-mt-1 md:ml-auto w-fit btn btn-secondary text-secondary-darker"
       target="_blank"
       rel="noopener">
        <?= $heroicons->printerHtml('mr-1 inline-block', 24, 24, ['aria-hidden' => 'true']); ?>
        <?= $escaper->escapeHtml(__('Print receipt')) ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php endif;?>
