<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\RecentlyViewedProducts;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var GraphqlViewModel $gqlViewModel */
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);

/** @var ProductPage $viewModelProducts */
$viewModelProducts = $viewModels->require(ProductPage::class);

/** @var RecentlyViewedProducts $recentlyViewed */
$recentlyViewed = $viewModels->require(RecentlyViewedProducts::class);

$currentProduct    = $viewModelProducts->getProduct();
$currentProductSku = $currentProduct ? $currentProduct->getSku() : '';

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

$noOfProductsToShow = (int) $storeConfig->getStoreConfig('catalog/recently_products/viewed_count');

/** @var Currency $viewModelCurrency */
$viewModelCurrency = $viewModels->require(Currency::class);

$gqlRecentlyViewedProductsQuery = 'query ($skus: [String!]!) {
products(filter: { sku: { in: $skus } }) {
    items {
      sku
      id
      name
      small_image {
        label
        url
      }
      url_key
      url_suffix
      visibility
      status
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
          final_price {
            value
            currency
          }
        }
      }
    }
  }
}';
?>
<script>
    function initRecentlyViewedProductsComponent() {
        const config = {
            useGraphQL: <?= $escaper->escapeJs($recentlyViewed->isFetchRecentlyViewedEnabled() ? 'true' : 'false') ?>,
            noOfProductsToShow: this.$root.dataset.productsToShow || <?= $escaper->escapeJs($noOfProductsToShow) ?>
        }

        function readRecentlyViewedFromStorage () {
            const data = hyva.getBrowserStorage().getItem('recently_viewed_products');
            return data ? JSON.parse(data).filter(product => {
                <?php /** Remove items that are invalid after switching config.useGraphQL to false */ ?>
                return config.useGraphQL || product.id;
            }) : [];
        }

        return {
            products: [],
            maxProductsToShow: config.noOfProductsToShow,
            hasProducts: false,
            loading: true,
            init() {
                this.$watch('products', products => {
                    this.hasProducts = products.length > 0;
                });

                this.getProducts();
            },
            minHeight() {
                return this.loading ? { minBlockSize: '38rem' } : {};
            },
            getProducts() {
                const recentlyViewedProductsArray = readRecentlyViewedFromStorage();
                let itemsToShow = [];

                if (recentlyViewedProductsArray.length > 0) {
                    // Avoid showing the current product
                    const start = '<?= $escaper->escapeJs($currentProductSku) ?>' === '' ? 0 : 1;
                    itemsToShow = recentlyViewedProductsArray.slice(start)
                }

                itemsToShow = itemsToShow.slice(0, this.maxProductsToShow);

                config.useGraphQL
                    ? this.fetchProducts(itemsToShow)
                    : this.renderRecentlyViewedProducts(itemsToShow);
            },
            fetchProducts(itemsToShow) {
                const skusToFetch = itemsToShow.map(product => product.sku);

                <?php /* It is not possible to query prices incl and excl tax from the GraphQL api */ ?>
                <?php /* If display incl + excl is required, ensure catalog/recently_products/synchronize_with_backend is set to No */ ?>
                const query = `<?= /** @noEscape */ $gqlViewModel->query("recently_viewed_products_query", $gqlRecentlyViewedProductsQuery) ?>`;
                const variables = JSON.stringify({ skus: skusToFetch });

                window.fetch(BASE_URL + 'graphql?' + new URLSearchParams({ query, variables }), {
                    method: 'GET',
                    headers: {
                        'Store': '<?= $escaper->escapeJs($viewModelStore->getStoreCode()) ?>',
                        'Content-Currency': '<?= $escaper->escapeJs($viewModelCurrency->getCurrentCurrencyCode()) ?>'
                    },
                })
                    .then((response) =>  response.json())
                    .then((result) => {
                            this.currency = (result &&
                                result.data &&
                                result.data.currency);

                            const responseProducts = (
                                result &&
                                result.data &&
                                result.data.products &&
                                result.data.products.items
                            ) || [];

                            // fix sorting of the response-products according to the sorting of the requested-products
                            const sortedProducts = [];
                            skusToFetch.forEach(sku => {
                                responseProducts.forEach(productData => {
                                    if (sku === productData.sku) {
                                        sortedProducts.push(productData);
                                    }
                                });
                            });
                            this.renderRecentlyViewedProducts(sortedProducts);
                        }
                    )
                    .finally(() => this.loading = false)
            },
            renderRecentlyViewedProducts(products) {
                this.products = products;
                this.loading = false;
            },
            addToWishlist() {
                const productId = this.product.id;
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'wishlist/index/add/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                            [{
                                type: "warning",
                                text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                            }], 5000
                        );
                    }
                }).then(response => {
                    if (!response) { return }
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: (response.success) ? "success" : "error",
                            text: (response.success)
                                ? "<?= $escaper->escapeHtml(
                                    __("%1 has been added to your Wish List.", __("Product"))
                                ) ?>" : response.error_message
                        }], 5000
                    );
                    window.dispatchEvent(new CustomEvent("reload-customer-section-data"));
                }).catch(function (error) {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            },
            addToCompare() {
                const productId = this.product.id;
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'catalog/product_compare/add/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    }
                }).catch(error => {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            },
            productUrl() {
                const baseUrl = '<?= $escaper->escapeUrl($block->getBaseUrl()) ?>';
                return this.product?.url_key
                    ? new URL(`${this.product?.url_key}${(this.product?.url_suffix || '')}`, baseUrl)
                    : '#';
            },
            productImgUrl() {
                return this.product?.small_image?.url || '';
            },
            productImgLabel() {
                return this.product?.small_image?.label || '';
            },
            productPrice() {
                return hyva.formatPrice(this.product?.price_range?.minimum_price?.final_price.value || 0);
            },
            productTaxPrice() {
                return hyva.formatPrice(this.product?.price_range?.minimum_price?.base_price.value || 0);
            },
            hasProducts() {
                return this.products && this.products.length;
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initRecentlyViewedProductsComponent', initRecentlyViewedProductsComponent);
    }, { once: true })
</script>
<?php $hyvaCsp->registerInlineScript() ?>
