<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
declare(strict_types=1);

/** @var $block \Magento\ReCaptchaUi\Block\ReCaptcha */
?>
<div class="control">
    <input type="hidden"
           value=""
           class="form-input"
           name="g-recaptcha-response"
    />
</div>
