<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

?>
<template x-if="isTooltipVisible()">
    <div class="absolute pointer-events-none select-none"
         :style="getTooltipPosition()"
    >
        <div class="absolute top-0 left-0 z-10 min-w-20 p-2 -mt-6 text-sm leading-tight text-black
                transform -translate-x-1/2 -translate-y-full bg-white rounded-lg shadow-lg text-center"
                :class="{'-translate-x-5' : isFirstItemCol()}"
        >
        <template x-if="isVisualSwatch(activeTooltipItem.attribute, activeTooltipItem.item)">
            <div class="inline-block border shadow-sm border-container"
                    :style="getTooltipImageStyle(activeTooltipItem.attribute, activeTooltipItem.item)"
            ></div>
        </template>
            <span class="mx-2 text-lg font-semibold whitespace-nowrap subtitle"
                    x-html="getTooltipLabel()"
            ></span>
        </div>
        <div class="absolute z-10 w-3 h-3 bg-white origin-top-left rotate-45 translate-x-4 -translate-y-8 shadow-xl" aria-hidden="true"></div>
    </div>
</template>
