<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty;

/** @var DefaultStockqty $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isMsgVisible()): ?>
    <p class="availability only flex items-center gap-x-2"
       title="<?= $escaper->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>"
    >
        <span>
            <?= /* @noEscape */ __('Only %1 left', "<span class='font-bold'>{$escaper->escapeHtml($block->getStockQtyLeft())}</span>") ?>
        </span>
    </p>
<?php endif ?>
