<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty;

/** @var DefaultStockqty $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isMsgVisible()): ?>
    <div class="my-4">
        <p class="availability only flex items-center gap-x-2
                before:w-3 before:h-3 before:rounded-full before:shrink-0 before:bg-orange-500"
           title="<?= $escaper->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>"
        >
            <span>
                <?= /* @noEscape */ __('Only %1 left', "<span class='font-bold'>{$escaper->escapeHtml($block->getStockQtyLeft())}</span>") ?>
            </span>
        </p>
    </div>
<?php endif ?>
