<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()) {
    return;
}
?>
<div class="container mx-auto px-5 py-6 items-center">
    <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
        <h3 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
            About / <span class="font-semibold"><?= $escaper->escapeHtml($product->getName()) ?></span>
        </h3>
    </div>
    <div class="card w-full">
        <div class="prose">
            <?= /** @noEscape */ $product->getDescription() ?>
        </div>
    </div>
</div>
