<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Template $block */
/** @var ProductPage $productViewModel */
$productViewModel = $block->getProductViewModel();
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $block->getAttributesViewModel();
/** @var Product $product */
$product = $productViewModel->getProduct();

if (!$product->getDescription()){
    return;
}
?>
<div class="container mx-auto px-5 py-6 items-center">
    <div class="container mx-auto flex pt-6 pb-3 mb-6 md:flex-row border-b-2 border-gray-300">
        <h3 class="text-gray-900 text-2xl title-font font-base text-center md:text-left w-full">
            About / <span class="font-semibold"><?= $product->getName() ?></span>
        </h3>
    </div>
    <div class="card w-full">
        <div class="prose">
            <?= $product->getDescription() ?>
        </div>
    </div>
</div>
