<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Catalog\Helper\Image;

/**  @var $block Gallery */

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}
/** @var Image $helper */
$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$smallWidth = $block->getImageAttribute('product_page_image_small', 'width', 90);
$smallHeight = $block->getImageAttribute('product_page_image_small', 'height', 90);
$mediumWidth = $block->getImageAttribute('product_page_image_medium', 'width', 700);
$mediumHeight = $block->getImageAttribute('product_page_image_medium', 'height', 700);
?>

<div id="gallery"
     x-data="initGallery()"
     class="lg:w-1/2 w-full lg:h-auto order-1"
    >
    <div class="relative">
        <img
            alt="main product photo"
            class="w-full h-auto object-cover object-center rounded"
            loading="lazy"
            src="<?= /* @noEscape */ $mainImageData ?>"
            width="<?= $mediumWidth ?>"
            height="<?= $mediumHeight ?>"
        />
        <template x-for="(image, index) in images" :key="index">
            <img
                alt="main product photo"
                class="absolute top-0 left-0 w-full h-auto object-fit object-center rounded"
                width="<?= $mediumWidth ?>"
                height="<?= $mediumHeight ?>"
                loading="lazy"
                :src="image.img"
                x-show="active===index+1"
                x-transition:enter="ease-out duration-500"
                x-transition:enter-start="opacity-0"
                x-transition:enter-end="opacity-100"
                x-transition:leave="ease-in duration-500"
                x-transition:leave-start="opacity-100"
                x-transition:leave-end="opacity-0"
            />
            </div>
        </template>
    </div>
    <div id="thumbs" class="flex flex-wrap">
        <template x-for="(image, index) in images" :key="index">
            <div>
                <a href="#" @click.prevent="active = index+1;" :class="{ 'border' : active === index+1}">
                    <img :src="image.thumb"
                         width="<?= $smallWidth ?>"
                         height="<?= $smallHeight ?>"
                    />
                </a>
            </div>
        </template>
    </div>
</div>
<script>
    function initGallery () {
        return {
            "active": 0,
            "images": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
        }
     }
</script>
