<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductPage;

/** @var Template $block */
/** @var ProductPage $productViewModel */
$productViewModel = $block->getProductViewModel();
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $block->getAttributesViewModel();
/** @var Product $product */
$product = $productViewModel->getProduct();

?>
<div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mb-6 lg:mb-0 order-2">
    <?php if ($productBrand = $product->getBrand()) { ?>
        <h2 class="text-sm title-font text-gray-500 tracking-widest">
            <?= $productBrand ?></h2>
    <?php } ?>

    <h1 class="text-gray-900 text-3xl title-font font-medium mb-3">
        <?= $product->getName() ?>
    </h1>

    <div class="mb-2 cursor-pointer" onclick="document.getElementById('customer-reviews').scrollIntoView({behavior: 'smooth'})">
        <?= $block->getChildHtml('product.info.review') ?>
    </div>

    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="product-description leading-relaxed mb-4 prose"><?= /* @noEscape */
            $shortDescription ?></div>
    <?php } ?>

    <div>
        <?php foreach ($block->getAttributes() as $attributeConfig) {
            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig);
            ?>
            <?php if ($value = $attribute['value'] ?? null) { ?>
                <div
                    class="flex border-t border-gray-300 py-2 last:mb-6 last:border-b <?= $attribute['value'] ?: "" ?>">
                    <span class="text-gray-500 text-left w-1/2"><?= $attribute['label'] ?></span>
                    <span class="ml-2 text-gray-900 text-left w-1/2"><?= $value ?></span>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
    <div class="flex sticky" style="top:6em;">
        <span class="title-font font-medium text-2xl text-gray-900">
            <?= $block->getChildHtml("product.price.final") ?>
        </span>
        <?php if ($product->isSaleable()) : ?>
            <?php
            /** @var \Magento\Framework\Data\Helper\PostHelper $postDataHelper */
            $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
            $postParams = json_decode(
                $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
            );
            ?>
            <form method="post"
                  action="<?= $block->escapeUrl($productViewModel->getAddToCartUrl($product)) ?>"
                  id="product_addtocart_form"<?php if ($product->getOptions(
            )) : ?> enctype="multipart/form-data"<?php endif; ?>
                  class="flex ml-auto"
            >
                <input type="hidden" name="product" value="<?= (int)$product->getId() ?>"/>
                <input type="hidden" name="selected_configurable_option" value=""/>
                <input type="hidden" name="related_product" id="related-products-field" value=""/>
                <input type="hidden" name="item" value="<?= (int)$block->getRequest()->getParam('id') ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="btn btn-primary"
                >
                    <svg class="h-6 w-6 border-current" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                    </svg>
                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </form>
        <?php endif; ?>
        <script>
            function initWishlist() {
                return {
                    addToWishlist: function addToWishlist(productId) {
                        var formKey = document.querySelector('input[name=form_key]').value;
                        var postUrl = BASE_URL + "wishlist/index/add/";
                        fetch(postUrl, {
                            "headers": {
                                "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                            },
                            "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + btoa(window.location.href),
                            "method": "POST",
                            "mode": "cors",
                            "credentials": "include"
                        }).then(function (response) {
                            if (response.redirected) {
                                window.location.href = response.url;
                                return;
                            } else if (response.ok) {
                                return response.json();
                            } else {
                                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                    [{
                                        type: "warning",
                                        text: "<?= $block->escapeHtml(__('Could not add item to wishlist.')) ?>"
                                    }], 5000
                                );
                            }
                        }).then(function (response) {
                            if (!response) {
                                return
                            }
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: (response.success) ? "success" : "error",
                                    text: (response.success)
                                        ? "<?= $block->escapeHtml(
                                            __("%1 has been added to your Wish List.", __("Product"))
                                        ) ?>"
                                        : response.error_message
                                }], 5000
                            );
                            var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                            window.dispatchEvent(reloadCustomerDataEvent);
                        }).catch(function (error) {
                            typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                                [{
                                    type: "error",
                                    text: error
                                }], 5000
                            );
                        });
                    }
                }
            }
        </script>
        <button x-data="initWishlist()"
                @click.prevent="addToWishlist(<?= $product->getId() ?>)"
                class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 hover:text-red-600 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
                 viewBox="0 0 24 24">
                <path
                    d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
        </button>
    </div>
</div>
