<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Magento\Catalog\Block\Product\Compare\ListCompare;
use Magento\Catalog\Helper\Product\Compare;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Wishlist\Helper\Data as WishlistHelper;

/** @var ListCompare $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Compare $compareHelper */
$compareHelper = $this->helper(Compare::class);
/** @var WishlistHelper $wishlistHelper */
$wishlistHelper = $this->helper(WishlistHelper::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
?>
<?php $total = $block->getItems()->getSize(); ?>
<?php if ($total): ?>
<script defer>
function initPrint() {
    return {
        print: function() {
            window.print();
        }
    };
}

function initCompare() {
    return {
        removeFromCompare: function(productId) {
            const formKey = document.querySelector('input[name=form_key]').value;
            const postUrl = BASE_URL + 'catalog/product_compare/remove/';
            const confirmMessage = "<?= $escaper->escapeHtml(__('Are you sure you want to remove this item from your Compare Products list?')) ?>";
            if (!window.confirm(confirmMessage)) {
                return;
            }

            fetch(postUrl, {
                "headers": {
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                },
                "body": "form_key="+ formKey + "&product="+productId+"&uenc="+btoa(window.location.href),
                "method": "POST",
                "mode": "cors",
                "credentials": "include"
            }).then(function (response) {
                if (response.redirected) {
                    window.location.href = response.url;
                } else if (response.ok) {
                    return response.json();
                } else {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "warning",
                            text: "<?= $escaper->escapeHtml(__('Could not remove item from compare.')) ?>"
                        }], 5000
                    );
                }
            }).then(function (response) {
                if (!response) { return; }
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: (response.success) ? "success" : "error",
                        text: (response.success)
                            ? "<?= $escaper->escapeHtml(__("You removed product %1 from the comparison list", __("Product"))) ?>"
                            : response.error_message
                    }], 5000
                );
                let reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                window.dispatchEvent(reloadCustomerDataEvent);
            }).catch(function (error) {
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: "error",
                        text: error
                    }], 5000
                );
            });
        }
    };
}

function initWishlist() {
    return {
        addToWishlist: function addToWishlist(productId){
            var formKey = document.querySelector('input[name=form_key]').value;
            var postUrl = BASE_URL+"wishlist/index/add/";
            fetch(postUrl, {
                "headers": {
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                },
                "body": "form_key="+ formKey + "&product="+productId+"&uenc="+btoa(window.location.href),
                "method": "POST",
                "mode": "cors",
                "credentials": "include"
            }).then(function (response) {
                if (response.redirected) {
                    window.location.href = response.url;
                } else if (response.ok) {
                    return response.json();
                } else {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "warning",
                            text: "<?= $escaper->escapeHtml(__('Could not add item to wishlist.')) ?>"
                        }], 5000
                    );
                }
            }).then(function (response) {
                if(!response) { return }
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: (response.success) ? "success" : "error",
                        text: (response.success)
                            ? "<?= $escaper->escapeHtml(__("%1 has been added to your Wish List.", __("Product"))) ?>"
                            : response.error_message
                    }], 5000
                );
                var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                window.dispatchEvent(reloadCustomerDataEvent);
            }).catch(function (error) {
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: "error",
                        text: error
                    }], 5000
                );
            });
        }
    }
}
</script>
<section>
    <button x-data="initPrint()"
            @click.prevent="print()"
            title="<?= $escaper->escapeHtmlAttr(__('Print This Page')) ?>">
        <span><?= $escaper->escapeHtml(__('Print This Page')) ?></span>
    </button>
    <table class="table-auto">
        <caption <?= $escaper->escapeHtml(__('Compare Products')) ?></caption>
        <tbody>
        <tr>
            <?php $index = 0; ?>
            <?php /** @var Product $product */ ?>
            <?php foreach ($block->getItems() as $product): ?>
                <?php if ($index++ === 0): ?>
                    <th scope="row">
                        <span><?= $escaper->escapeHtml(__('Product')) ?></span>
                    </th>
                <?php endif; ?>
                <td>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl($product)) ?>"
                       title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>">
                        <?= $block->getImage($product, 'product_comparison_list')->toHtml() ?>
                    </a>
                    <strong>
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl($product)) ?>"
                           title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>">
                            <?= $escaper->escapeHtml($product->getName()) ?>
                        </a>
                    </strong>
                    <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                    <?= /* @noEscape */ $block->getProductPrice($product, '-compare-list-top') ?>
                    <div>
                        <div>
                            <?php if ($product->isSaleable()): ?>
                                <form data-role="tocart-form"
                                      action="<?= $escaper->escapeUrl($compareHelper->getAddToCartUrl($product)) ?>"
                                      method="post">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            class="w-auto mr-auto btn btn-primary justify-center text-sm px-4 md:px-2 lg:px-4"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                    >
                                        <svg class="h-6 w-6 border-current inline" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
                                        </svg>
                                        <span class="inline md:hidden lg:inline"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($product->getIsSalable()): ?>
                                    <div>
                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                    </div>
                                <?php else: ?>
                                    <div> 
                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <?php if ($wishlistHelper->isAllow()): ?>
                            <button x-data="initWishlist()"
                                    @click.prevent="addToWishlist(<?= (int)$product->getId() ?>)"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                    class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 hover:text-red-600 ml-4">
                                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
                                     viewBox="0 0 24 24">
                                    <path
                                        d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>
                                </svg>
                            </button>
                        <?php endif; ?>
                        <button x-data="initCompare()"
                                @click.prevent="removeFromCompare(<?= (int)$product->getId() ?>)"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Remove Product')) ?>"
                                class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 hover:text-red-600 ml-4"
                                title="<?= $escaper->escapeHtmlAttr(__('Remove Product')) ?>">
														<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" class="w-5 h-5">
															<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
														</svg>
                        </button>
                    </div>
                </td>
            <?php endforeach; ?>
        </tr>
        </tbody>
        <tbody>
        <?php foreach ($block->getAttributes() as $attribute): ?>
            <?php $index = 0; ?>
            <?php if ($block->hasAttributeValueForProducts($attribute)): ?>
                 <tr>
                    <?php /** @var Product $product */ ?>
                    <?php foreach ($block->getItems() as $product): ?>
                        <?php if ($index++ === 0): ?>
                            <th scope="row">
                                <span>
                                    <?= $escaper->escapeHtml($attribute->getStoreLabel() ?: __($attribute->getFrontendLabel())) ?>
                                </span>
                            </th>
                        <?php endif; ?>
                        <td>
                            <div>
                                <?php switch ($attribute->getAttributeCode()) {
                                    case 'price': ?>
                                        <?=
                                        /* @noEscape */ $block->getProductPrice(
                                            $product,
                                            '-compare-list-' . $attribute->getCode()
                                        )
                                        ?>
                                        <?php break;
                                    case 'small_image': ?>
                                        <?= $block->getImage($product, 'product_small_image')->toHtml(); ?>
                                        <?php break;
                                    default :?>
                                            <?php
                                            $attributeData = $attributesViewModel->getAttributeData(
                                                $attribute,
                                                $product
                                            )
                                            ?>
                                            <?= $escaper->escapeHtml($attributeData['value']) ?>
                                        <?php break;
                                } ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</section>
<?php if (!$block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form]": {
            "catalogAddToCart": {}
        }
    }
    </script>
<?php endif; ?>
<?php else: ?>
<div>
    <div><?= $escaper->escapeHtml(__('You have no items to compare.')) ?></div>
</div>
<?php endif; ?>
