<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<div class="container">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
             alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
        />
</div>

<script>
    "use strict";

    // Invalidate existing private content
    const browserStorage = hyva.getBrowserStorage();
    if (browserStorage) {
        browserStorage.removeItem('mage-cache-storage');
    }

    window.addEventListener("private-content-loaded", function(event) {
        const sectionData = event.detail.data;
        if (sectionData.loggedAsCustomer && sectionData.loggedAsCustomer.adminUserId) {
            window.location.href = "<?= /* @noEscape */ $block->getUrl('customer/account/index') ?>"
        }
    });

</script>
