<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="loading-mask">
    <div class="loader">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
             alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
             style="position: absolute;">
    </div>
</div>

<script>
    "use strict";

    // Invalidate existing private content
    const browserStorage = hyva.getBrowserStorage();
    if (browserStorage) {
        browserStorage.removeItem('mage-cache-storage');
    }

    window.addEventListener("private-content-loaded", function(event) {
        var sectionData = event.detail.data;
        if (sectionData.loggedAsCustomer && sectionData.loggedAsCustomer.adminUserId) {
            window.location.href = "<?= /* @noEscape */ $block->getUrl('customer/account/index') ?>"
        }
    });

</script>
