<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Store as StoreViewModel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\Cart\GraphQlQueries;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var GraphQlQueries $viewModelCart */
$viewModelCart = $viewModels->require(GraphQlQueries::class);
/** @var StoreViewModel $viewModelStore */
$viewModelStore = $viewModels->require(StoreViewModel::class);
/** @var GraphqlViewModel $viewModelGraphQl */
$viewModelGraphQl = $viewModels->require(GraphqlViewModel::class);
?>
<script>
    function initCart() {
        return {
            cartId: null,
            customerToken: null,
            cartData: [],
            cartEmpty: true,
            isLoading: true,
            isTouchDevice: false,
            showCouponForm: false,
            getCartQuery(cartId) {
                return <?= /** @noEscape */ json_encode($viewModelGraphQl->query(
                    'cart_query',
                    '{cart (cart_id: "%cartId") {' . /* @noEscape */ $viewModelCart->getCartGraphQlQuery() . '}}'
                )); ?>.replace('%cartId', cartId)
            },
            getCustomerCartQuery() {
                return <?= /** @noEscape */ json_encode($viewModelGraphQl->query(
                    'customer_cart_query',
                    '{customerCart {' . /* @noEscape */ $viewModelCart->getCartGraphQlQuery() . '}}'
                )); ?>
            },
            getCart() {
                this.isLoading = true;
                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                        credentials: 'include',
                        body: JSON.stringify({
                            query: (
                                this.customerToken &&
                                this.getCustomerCartQuery()) ||
                                this.getCartQuery(this.cartId)
                        })
                    }
                ).then((response) => {
                        return response.json()
                    }
                ).then((data) => {
                    if (data && data.errors) {
                        this.initErrorMessages(data.errors);
                    } else {
                        this.cartData = (data && data.data && (data.data.customerCart || data.data.cart)) || [];
                        this.updateCartDataDependencies();
                    }
                }).catch(error => {
                    console.error(error);
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: "<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>"
                        }], 10000
                    );
                }).finally(() => {
                    this.isLoading = false;
                });
            },
            getCartByCustomerSectionData(data) {
                if (data && data.cart && data.cart.cartId) {
                    this.cartId = data.cart.cartId;
                    this.customerToken = data.customer.signin_token
                    if (data.cart.summary_count !== this.cartData.total_quantity) {
                        this.getCart();
                    }
                } else {
                    this.cartEmpty = true;
                    this.isLoading = false;
                }
            },
            isTouchEnabled() {
                this.isTouchDevice = ('ontouchstart' in window) ||
                    (navigator.maxTouchPoints > 0) ||
                    (navigator.msMaxTouchPoints > 0);
            },
            updateCartDataDependencies() {
                this.showCouponForm = this.cartData.applied_coupons;
                this.cartEmpty = !(
                    this.cartData &&
                    this.cartData.items &&
                    Object.keys(this.cartData.items).length
                );
            },
            dispatchCouponMutationRequest() {
                if (!this.cartData.applied_coupons && document.getElementById('coupon_code').value === '') {
                    dispatchMessages([{
                        type: 'error',
                        text: '<?= $escaper->escapeJs(__('Please enter a coupon code')) ?>'
                    }], 5000)
                } else {
                    this.mutateCouponCode();
                }
            },
            mutateCouponCode() {
                this.isLoading = true;

                var couponCode = document.getElementById('coupon_code').value;
                var couponQuery = couponCode
                    ? `<?= /** @noEscape */ $viewModelGraphQl->query(
                        'cart_coupon_add_mutation',
                        'mutation {' . $viewModelCart->getCouponAddQuery() . '}'
                    ) ?>`
                    : `<?= /** @noEscape */ $viewModelGraphQl->query(
                        'cart_coupon_remove_mutation',
                        'mutation {' . $viewModelCart->getCouponRemoveQuery() . '}'
                    ) ?>`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8',
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                        body: JSON.stringify({query: couponQuery})
                    }
                ).then((response) => {
                        return response.json()
                    }
                ).then((data) => {
                    this.clearErrorMessages();
                    if (data && data.errors) {
                        this.initErrorMessages(data.errors);
                        this.getCart();
                    } else {
                        this.cartData = (
                            data &&
                            data.data &&
                            (
                                (data.data.removeCouponFromCart && (data.data.removeCouponFromCart.cart)) ||
                                (data.data.applyCouponToCart && (data.data.applyCouponToCart.cart))
                            )
                        ) || [];
                        this.updateCartDataDependencies();
                        document.getElementById('coupon_code').value = '';
                    }
                    this.reloadCustomerData();
                }).catch(error => {
                    console.error(error);
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: "<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>"
                        }], 10000
                    );
                }).finally(() => {
                    this.isLoading = false;
                });
            },
            clearErrorMessages() {
                window.dispatchEvent(new CustomEvent('clear-messages'));
            },
            initErrorMessages(errors) {
                var messages = [];
                for (var error in Object.keys(errors)) {
                    messages.push({type: 'error', text: errors[error].message});
                }
                dispatchMessages(messages)
            },
            mutateItemQty(itemId, qty) {
                this.isLoading = true;

                var cartItemUpdateQuery = `<?= /** @noEscape */ $viewModelGraphQl->query(
                    'cart_item_update_mutation',
                    'mutation {' . $viewModelCart->getCartItemUpdateQuery() . '}'
                ) ?>`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8',
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                        body: JSON.stringify({query: cartItemUpdateQuery.replace('%cartId', this.cartId)})
                    }
                ).then((response) => {
                        return response.json()
                    }
                ).then((data) => {
                    this.clearErrorMessages();
                    if (data.errors) {
                        this.initErrorMessages(data.errors);
                        this.getCart();

                    } else {
                        this.cartData = (
                            data &&
                            data.data &&
                            (data.data.updateCartItems && (data.data.updateCartItems.cart))
                        ) || [];
                        this.updateCartDataDependencies();
                    }
                    this.reloadCustomerData();
                }).catch(error => {
                    console.error(error);
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: "<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>"
                        }], 10000
                    );
                }).finally(() => {
                    this.isLoading = false;
                });
            },
            mutateItemRemove(itemId) {
                this.isLoading = true;
                var cartItemRemoveQuery = `<?= /** @noEscape */ $viewModelGraphQl->query(
                    'cart_item_remove_mutation',
                    'mutation {' . $viewModelCart->getCartItemRemoveQuery() . '}'
                )?>`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8',
                            'Store': '<?= /* @noEscape */ $viewModelStore->getStoreCode() ?>'
                        },
                        body: JSON.stringify({query: cartItemRemoveQuery})
                    }
                ).then((response) => {
                        return response.json()
                    }
                ).then((data) => {
                    this.clearErrorMessages();
                    if (data.errors) {
                        this.initErrorMessages(data.errors);
                        this.getCart();

                    } else {
                        this.cartData = (
                            data &&
                            data.data &&
                            (
                                data.data.removeItemFromCart &&
                                (data.data.removeItemFromCart.cart)
                            )
                        ) || [];
                        this.updateCartDataDependencies();
                    }
                    this.reloadCustomerData();
                }).catch(error => {
                    console.error(error);
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: "<?= $escaper->escapeJs(__("Something went wrong. Please try again.")) ?>"
                        }], 10000
                    );
                }).finally(() => {
                    this.isLoading = false;
                });
            },
            reloadCustomerData() {
                var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                window.dispatchEvent(reloadCustomerDataEvent);
            }
        }
    }
</script>
