<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\Cart\GraphQlQueries;

/** @var $block Template */
/** @var $escaper Escaper */
/** @var $viewModelCart Cart */
$viewModelCart = $block->getData('viewModelCart');
?>
<script>

    <?= $block->getChildHtml('js_localstorage_config') ?>

    function initCart() {
        return {
            cartId: getConfigFromLocalStorage(activeSource.cartId),
            cartData: [],
            cartEmpty: true,
            isLoading: true,
            isTouchDevice: false,
            showCouponForm: false,
            getCartId: function getCartId() {
                this.cartId = getConfigFromLocalStorage(activeSource.cartId);
                return this.cartId;
            },
            getSignInToken: function getSignInToken() {
                return getConfigFromLocalStorage(activeSource.token);
            },
            getCartQuery: function getCartQuery(cartId) {
                return <?= /** @noEscape */ json_encode(
                    '{cart (cart_id: "%cartId") {' . /* @noEscape */ $viewModelCart->getCartGraphQlQuery() . '}}'
                ); ?>.replace('%cartId', cartId)
            },
            getCustomerCartQuery: function getCustomerCartQuery() {
                return <?= /** @noEscape */ json_encode(
                    '{customerCart {' . /* @noEscape */ $viewModelCart->getCartGraphQlQuery() . '}}'
                ); ?>
            },
            getCart() {
                var $this = this;
                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        credentials: 'include',
                        body: JSON.stringify({
                            query: ($this.getSignInToken() && $this.getCustomerCartQuery()) || this.getCartQuery(this.getCartId())
                        })
                    }
                ).then(function (response) {
                        return response.json()
                    }
                ).then(function (data) {
                    if (data && data.errors) {
                        $this.initErrorMessages(data.errors);
                    } else {
                        $this.cartData = (data && data.data && (data.data.customerCart || data.data.cart)) || [];
                        $this.updateCartDataDependencies();
                    }
                    $this.isLoading = false;
                });
            },
            getCartByLocalStorage() {
                if (this.getCartId()) {
                    this.getCart();
                }
            },
            getCartByCustomerSectionData() {
                if (this.getCartId()) {
                    this.getCart();
                } else {
                    this.cartEmpty = true;
                }
            },
            formatPrice(price) {
                return price.toLocaleString(false, {
                    style: 'currency',
                    currency: this.cartData.prices.subtotal_excluding_tax.currency
                })
            },
            isTouchEnabled: function () {
                this.isTouchDevice = ('ontouchstart' in window) ||
                    (navigator.maxTouchPoints > 0) ||
                    (navigator.msMaxTouchPoints > 0);
            },
            updateCartDataDependencies() {
                this.showCouponForm = this.cartData.applied_coupons;
                if (this.cartData && this.cartData.items && Object.keys(this.cartData.items).length) {
                    this.cartEmpty = false;
                } else {
                    this.cartEmpty = true;
                }
            },
            dispatchCouponMutationRequest: function () {
                if (!this.cartData.applied_coupons && document.getElementById('coupon_code').value == '') {
                    dispatchMessages([{
                        type: 'error',
                        text: '<?= $escaper->escapeJs(__('Please enter a coupon code')) ?>'
                    }], 5000)
                } else {
                    this.mutateCouponCode();
                }
            },
            mutateCouponCode() {
                this.isLoading = true;
                var $this = this;

                var couponCode = document.getElementById('coupon_code').value;
                var couponQuery = couponCode ? `mutation {<?= /** @noEscape */ $viewModelCart->getCouponAddQuery(
                ) ?>}` : `mutation {<?= /** @noEscape */ $viewModelCart->getCouponRemoveQuery() ?>}`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8'
                        },
                        body: JSON.stringify({query: couponQuery})
                    }
                ).then(function (response) {
                        return response.json()
                    }
                ).then(function (data) {
                    $this.clearErrorMessages();
                    if (data && data.errors) {
                        $this.initErrorMessages(data.errors);
                        $this.getCart();
                    } else {
                        $this.cartData = (data && data.data && ((data.data.removeCouponFromCart && (data.data.removeCouponFromCart.cart)) || (data.data.applyCouponToCart && (data.data.applyCouponToCart.cart)))) || [];
                        $this.updateCartDataDependencies();
                        document.getElementById('coupon_code').value = '';
                    }
                    $this.isLoading = false;
                });
            },
            clearErrorMessages() {
                dispatchMessages([]);
            },
            initErrorMessages(errors) {
                var messages = [];
                for (var error in Object.keys(errors)) {
                    messages.push({type: 'error', text: errors[error].message});
                }
                dispatchMessages(messages)
            },
            mutateItemQty: function (itemId, qty) {
                var $this = this;
                $this.isLoading = true;

                var cartItemUpdateQuery = `mutation {<?= /** @noEscape */ $viewModelCart->getCartItemUpdateQuery() ?>}`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8'
                        },
                        body: JSON.stringify({query: cartItemUpdateQuery.replace('%cartId', this.getCartId)})
                    }
                ).then(function (response) {
                        return response.json()
                    }
                ).then(function (data) {
                    $this.clearErrorMessages();
                    if (data.errors) {
                        this.initErrorMessages(data.errors);
                        this.getCart();

                    } else {
                        $this.cartData = (data && data.data && (data.data.updateCartItems && (data.data.updateCartItems.cart))) || [];
                        $this.updateCartDataDependencies();
                    }
                    $this.isLoading = false;
                    $this.reloadCustomerData();
                });
            },
            mutateItemRemove: function (itemId) {
                var $this = this;
                $this.isLoading = true;
                var cartItemRemoveQuery = `mutation {<?= /** @noEscape */ $viewModelCart->getCartItemRemoveQuery() ?>}`;

                fetch('<?= $escaper->escapeUrl($block->getBaseUrl()) ?>graphql', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json;charset=utf-8'
                        },
                        body: JSON.stringify({query: cartItemRemoveQuery})
                    }
                ).then(function (response) {
                        return response.json()
                    }
                ).then(function (data) {
                    $this.clearErrorMessages();
                    if (data.errors) {
                        $this.initErrorMessages(data.errors);
                        $this.getCart();

                    } else {
                        $this.cartData = (data && data.data && (data.data.removeItemFromCart && (data.data.removeItemFromCart.cart))) || [];
                        $this.updateCartDataDependencies();
                    }
                    $this.isLoading = false;
                    $this.reloadCustomerData();
                });
            },
            reloadCustomerData: function () {
                var reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                window.dispatchEvent(reloadCustomerDataEvent);
            }
        }
    }
</script>
