<?php

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info\Buttons;

/** @var $escaper Escaper */
/** @var $block Buttons */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<div class="flex items-center justify-center md:justify-end my-4 md:my-0">
    <?php $order = $block->getOrder() ?>
    <a href="<?= $block->escapeUrl($block->getUrl('*/*/printCreditmemo', ['order_id' => $order->getId()])) ?>"
       class="ml-6 btn btn-secondary text-secondary-darker"
       target="_blank"
       rel="noopener">
        <svg class="mr-1 inline-block" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="24" height="24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
        </svg>
        <span><?= $block->escapeHtml(__('Print All Refunds')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
