<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit;
use Magento\Wishlist\Model\Item;

/** @var Edit $block */
/** @var Escaper $escaper */

/** @var Item $item */
$item = $block->getItem();
$product = $item->getProduct();

// The product url contains a hash with selected product options
// We're going to use that hash
$productUrl = $block->getProductUrl($item);
$urlHash = explode('#', $productUrl);
// it would be nicer if we would one day extend the getItemConfigureUrl instead
$configureUrl = $block->getItemConfigureUrl($item);

// we add the hash from productUrl to the configureUrl
$editProductUrl = $configureUrl . (count($urlHash) > 1 ? '#' . $urlHash[1] : '');
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="action edit btn btn-secondary inline-flex mr-2 p-2"
       href="<?= $escaper->escapeUrl($editProductUrl) ?>">
        <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" size="16" class="h-5 w-5">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z">
            </path>
        </svg>
        <span class="sr-only"><?= $escaper->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
