<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ProductPage;

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var $block AbstractProduct */
/** @var $escaper Escaper */

/** @var ProductPage $productViewModel */
$productViewModel = $block->getData('product_view_model');

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var $product Magento\Catalog\Model\Product */
$product = $block->getData('product');
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');

if (!$product) return; ?>
<div class="item product product-item w-full md:w-1/2 xl:w-1/3 p-6 flex flex-col">
    <?php
    $productImage = $block->getImage($product, $imageDisplayArea);
    ?>
    <?php // Product Image ?>
    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
       class="product photo product-item-photo"
       tabindex="-1">
        <img class="hover:grow hover:shadow-lg"
             src="<?= $productImage->getImageUrl() ?>"
             width="<?= $productImage->getWidth() ?>"
             height="<?= $productImage->getHeight() ?>"
        />
    </a>
    <?php
    $productNameStripped = $block->stripTags($product->getName(), null, true);
    ?>
    <div class="pt-3 flex items-center justify-center text-primary">
        <a class="product-item-link"
           href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
            <?= /* @noEscape */
            $catalogOutputHelper->productAttribute($product, $product->getName(), 'name') ?>
        </a>

    </div>
    <p class="pt-1 text-gray-900"><?= /* @noEscape */
        $block->getProductPrice($product) ?></p>
    <div class="pt-3 flex justify-center">
        <a class="w-auto mr-auto btn btn-primary justify-center text-sm px-4 md:px-2 lg:px-4"
           href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
            <svg class="h-6 w-6 border-current inline" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
            </svg>
            <span class="inline md:hidden lg:inline">Add to cart</span>
        </a>
        <button
            class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-auto">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5"
                 viewBox="0 0 24 24">
                <path
                    d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
        </button>
    </div>
</div>
