<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
?>

<section class="pb-6 md:py-6 text-gray-700 body-font grid grid-cols-1 gap-5 items-start md:grid-cols-[42%_minmax(0px,1fr)] lg:grid-cols-2 lg:gap-x-10 ">
    <?= $block->getChildHtml('product.media') ?>
    <?= $block->getChildHtml('product.info') ?>
</section>

<section>
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>

<?= $block->getChildHtml('product.info.details'); ?>

<section>
    <?= $block->getChildHtml('related') ?>
    <?= $block->getChildHtml('upsell') ?>
    <?= $block->getChildHtml('review_list') ?>
    <?= $block->getChildHtml('review_form') ?>
</section>
