<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();
?>
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-2 py-6 md:flex-row flex-col items-center">
        <div class="flex flex-wrap md:text-left text-center order-first w-full">
            <?= $block->getChildHtml('product.info') ?>
            <?= $block->getChildHtml('product.media') ?>
        </div>
    </div>
</section>
<section>
    <?= $block->getChildHtml('related') ?>
    <?= $block->getChildHtml('upsell') ?>
</section>
