<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPage;
use Magento\Catalog\Block\Product\View\Options;
use Magento\Catalog\Model\Product\Option;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Options $block */
/** @var ViewModelRegistry $viewModels */
/** @var Option $option */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

$options = $block->decorateArray($block->getOptions());

?>
<?php if (count($options)): ?>
    <script defer>
        function initOptions() {
            return {
                optionConfig: <?= /* @noEscape */ $block->getJsonConfig() ?>,
                productFinalPrice: false,
                customOptionPrices: [],
                refs: [],
                formatPrice(value, showSign) {
                    var formatter = new Intl.NumberFormat(
                        document.documentElement.lang,
                        {
                            style: 'currency',
                            currency: '<?= /** @noEscape */ $productViewModel->getCurrencyData()['code']; ?>',
                            signDisplay: showSign ? "always" : "auto"
                        }
                    );
                    return (typeof Intl.NumberFormat.prototype.formatToParts) ?
                        formatter.formatToParts(value).map(({type, value}) => {
                            switch (type) {
                                case 'currency':
                                    return '<?= $productViewModel->getCurrencyData()['symbol'] ?: ""; ?>' || value;
                                case 'minusSign':
                                    return '- ';
                                case 'plusSign':
                                    return '+ ';
                                default :
                                    return value;
                            }
                        }).reduce((string, part) => string + part) :
                        formatter.format(value);
                },
                getFormattedOptionPrice(optionId) {
                    if (this.customOptionPrices[optionId]) {
                        const showSign = true;
                        return this.formatPrice(this.customOptionPrices[optionId], showSign);
                    }
                    return false;
                },
                calculateOptionPrices() {
                    for (const [customOptionId, customOption] of Object.entries(this.optionConfig)) {
                        if (customOption.prices) {
                            this.customOptionPrices[customOptionId] =
                                this.calculateOptionPrice(customOption,customOptionId);
                        } else {
                            for (const [childCustomOptionId, childCustomOption] of Object.entries(customOption)) {
                                this.customOptionPrices[customOptionId + '_' + childCustomOptionId] =
                                    this.calculateOptionPrice(childCustomOption,customOptionId,childCustomOptionId);
                            }
                        }
                    }

                    window.dispatchEvent(
                        new CustomEvent(
                            "update-custom-option-prices",
                            {detail: this.customOptionPrices}
                        )
                    );
                },
                calculateOptionPrice(customOption, customOptionId, childCustomOptionId) {
                    const customOptionCode = customOptionId + (childCustomOptionId ? '-' + childCustomOptionId : '') ;

                    const optionElement = this.refs && this.refs['option-'+customOptionCode];

                    let price = customOption.prices.finalPrice.amount;

                    if (this.productFinalPrice &&
                        optionElement &&
                        optionElement.dataset.priceAmount &&
                        optionElement.dataset.priceType
                    ) {
                        price = optionElement.dataset.priceType !== 'percent' ?
                            optionElement.dataset.priceAmount :
                            this.productFinalPrice * (optionElement.dataset.priceAmount / 100)
                    }

                    return price;
                },
                updateCustomOptionValue($dispatch, customOptionId, target) {
                    let active;
                    switch (target.type) {
                        case 'text':
                        case 'textarea':
                        case 'file':
                            active = !!target.value;
                        break;
                        case 'checkbox':
                            active = target.checked;
                        break;
                        case 'radio':
                            document.querySelectorAll('input[name="'+target.name+'"]').forEach(input => {
                                // unset sibling radio buttons
                                input.dataset &&
                                input.dataset.optionId &&
                                input !== target && $dispatch('update-custom-option-active',
                                    {
                                        customOptionId: input.dataset.optionId,
                                        active: false
                                    }
                                );
                            })
                            active = target.checked;
                        break;
                    }
                    $dispatch('update-custom-option-active', { customOptionId, active });
                },
                eventListeners: {
                    ['@update-product-final-price.window'](event) {
                        this.productFinalPrice = event.detail;
                        this.calculateOptionPrices();
                    }
                }
            }
        }
    </script>
    <h2 class="text-gray-900 text-xl title-font font-medium mb-4">
        <?= $escaper->escapeHtml(__('Customizable Options:')) ?>
    </h2>
    <div x-data="initOptions()"
         x-init="
            refs = $refs;
            $nextTick(() => { calculateOptionPrices() })
         "
         x-spread="eventListeners"
         class="mb-6">
    <?php foreach ($options as $option):?>
        <?= $block->getOptionHtml($option) ?>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
