<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\LocaleFormatter;
use Magento\Catalog\Helper\Data;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation\FilterRenderer;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var FilterRenderer $block */
/** @var Escaper $escaper */
/** @var LocaleFormatter $localeFormatter */

$catalogHelper = $this->helper(Data::class);

/** @var array $filterItems */
?>

<ol class="items" aria-label="<?= $escaper->escapeHtmlAttr(__('%1 filter options', $block->getFilterTitle())) ?>">
<?php foreach ($filterItems as $filterItem): ?>
    <li>
        <?php if ($filterItem->getCount() > 0): ?>
            <a
                href="<?= $escaper->escapeUrl($filterItem->getUrl()) ?>"
                class="flex justify-between py-1 hover:text-black"
                aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr(
                    ((int)$filterItem->getCount() == 1)
                        ? __('Filter: %1, 1 available product', $filterItem->getLabel() )
                        : __('Filter: %1, %2 available products', $filterItem->getLabel(), $filterItem->getCount() )
                ) ?>"
            >
                <span><?= /* @noEscape */ $filterItem->getLabel() ?></span>
                <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count text-primary">(<?= /* @noEscape */ $localeFormatter->formatNumber((int)$filterItem->getCount()) ?>)</span>
                <?php endif; ?>
            </a>
        <?php else: ?>
            <span class="flex justify-between py-1 hover:text-black">
                    <span><?= /* @noEscape */ $filterItem->getLabel() ?></span>
                <?php if ($catalogHelper->shouldDisplayProductCountOnLayer()): ?>
                    (<span class="count text-primary"><?= /* @noEscape */ $localeFormatter->formatNumber((int)$filterItem->getCount()) ?></span>)
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
