<?php
/**
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

/** @var $block State */

use Magento\LayeredNavigation\Block\Navigation\State;

// phpcs:disable Generic.Files.LineLength.TooLong
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<div class="filter-current bg-background-lighter border border-background p-4 md:px-8" x-data="{ open: true }">
    <div class="filter-options-title flex justify-between items-center cursor-pointer"
         @click="open = !open">
        <strong><?= $block->escapeHtml(__('Active filtering')) ?></strong>
        <span class="py-1 px-1 rounded border border-background">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="transition-transform transform duration-300 ease-in-out" :class="open ? 'rotate-180' : ''">
                <path d="M19 9L12 16L5 9" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </span>
    </div>
    <div class="items pt-1 pb-3" x-show="open">
        <?php foreach ($_filters as $_filter): ?>
            <div class="item flex justify-between items-center">
                <span>
                    <span class="filter-label block"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                    <span class="filter-value text-sm block"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
                </span>
                <span>
                    <a class="py-2 px-2 text-center block action remove text-primary hover:text-primary-darker" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove This Item')) ?>">
                        <svg class="fill-current" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M9 2C8.62123 2 8.27497 2.214 8.10557 2.55279L7.38197 4H4C3.44772 4 3 4.44772 3 5C3 5.55228 3.44772 6 4 6L4 16C4 17.1046 4.89543 18 6 18H14C15.1046 18 16 17.1046 16 16V6C16.5523 6 17 5.55228 17 5C17 4.44772 16.5523 4 16 4H12.618L11.8944 2.55279C11.725 2.214 11.3788 2 11 2H9ZM7 8C7 7.44772 7.44772 7 8 7C8.55228 7 9 7.44772 9 8V14C9 14.5523 8.55228 15 8 15C7.44772 15 7 14.5523 7 14V8ZM12 7C11.4477 7 11 7.44772 11 8V14C11 14.5523 11.4477 15 12 15C12.5523 15 13 14.5523 13 14V8C13 7.44772 12.5523 7 12 7Z"/>
                        </svg>
                    </a>
                </span>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($block->getLayer()->getState()->getFilters()): ?>
        <div class="block-actions filter-actions">
            <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
               class="text-xs text-primary hover:text-primary-darker"><?= $block->escapeHtml(__('Clear All')) ?></a>
        </div>
    <?php endif; ?>
</div>
<?php endif; ?>
