<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var $block Navigation */
/** @var $escaper Escaper */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block Navigation
 */
?>
<?php if ($block->canShowBlock()) : ?>
    <div class="block border border-background p-4 md:border-0 md:py-0 md:px-0 my-6" x-data="initLayeredNavigation()" x-init="checkIsMobileResolution()">
        <div class="block-title h-10 flex items-center justify-between" @click="blockOpen = !blockOpen">
            <span class="text-primary text-md md:text-3xl"><?= $escaper->escapeHtml(__('Shop By')) ?></span>
            <span class="py-1 px-1 rounded border border-background" x-show="isMobile">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     class="transition-transform transform duration-300 ease-in-out"
                     :class="blockOpen ? 'rotate-180' : ''">
                    <path d="M19 9L12 16L5 9" stroke="#4A5568" stroke-width="2" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </span>
        </div>
        <div class="block-content filter-content pt-3 md:pt-6" x-show="isMobile && blockOpen || !isMobile">
            <?= $block->getChildHtml('state') ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <div class="filter-option md:border md:border-background py-4 md:px-8 my-4" x-data="{ open: true }">
                        <div
                            class="filter-options-title flex justify-between items-center cursor-pointer hover:text-secondary-darker"
                            @click="open = !open">
                            <span class="title text-md md:text-lg">
                                <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                </span>
                            <span class="py-1 px-1 rounded border border-background">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg"
                                     class="transition-transform transform duration-300 ease-in-out"
                                     :class="open ? 'rotate-180' : ''">
                                    <path d="M19 9L12 16L5 9" stroke="#4A5568" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round"/>
                                </svg>
                            </span>
                        </div>
                        <div class="filter-options-content pt-3" x-show="open">
                            <?= /* @noEscape */
                            $block->getChildBlock('renderer')->render($filter) ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution: function () {
                    this.isMobile = window.outerWidth < 768
                }
            }
        }
    </script>
<?php endif; ?>
