<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);
$productName = $block->getItem()->getName()
?>
<a
    href="#"
    title="<?= $escaper->escapeHtml(__('Remove %1', $productName)) ?>"
    class="action action-delete"
    x-data="{}"
    @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getDeletePostJson() ?>)'
    aria-label="<?= $escaper->escapeHtml(__('Remove %1', $productName)) ?>"
>
    <?= $heroicons->trashHtml('w-6 h-6', 24, 24, ['role' => 'presentation', 'focusable' => 'false']) ?>
    <span class="sr-only">
        <?= $escaper->escapeHtml(__('Remove %1', $productName)) ?>
    </span>
</a>
