<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);
$item = $block->getItem();

if ($item->getProductType() === 'configurable') {
    $productOptions = $item->getProduct()->getTypeInstance()->getOrderOptions($item->getProduct());
    $productName = $productOptions["simple_name"];
} else {
    $productName = $item->getName();
}
?>
<button
    class="flex action action-delete"
    x-data="{}"
    @click.prevent='
        hyva.postForm(<?= /* @noEscape */ $block->getDeletePostJson() ?>);
        $dispatch(
            "cart-item-removed",
            [{
                "product_sku": "<?= $escaper->escapeJs($item->getSku()); ?>",
                "product_name": "<?= $escaper->escapeJs($item->getName()); ?>",
                "product_price_value": "<?= $escaper->escapeJs($item->getPrice()); ?>",
                "quantity": "<?= $escaper->escapeJs($item->getQty()); ?>",
            }]
        );
    '
    aria-label="<?= $escaper->escapeHtmlAttr(__('Remove %1', $productName)) ?>"
    type="button"
>
    <?= $heroicons->trashHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
</button>
