<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var $storeConfig StoreConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$siteKey = $storeConfig->getStoreConfig('recaptcha_frontend/type_recaptcha_v3/public_key');
?>
<?php if ($siteKey): ?>
<script>
    'use strict';

    (function() {

        const recaptchaUrl = "https://www.google.com/recaptcha/api.js?render=<?= $escaper->escapeJs($siteKey) ?>";

        const loadRecaptchaScript = (event) => {
            if (typeof window.grecaptcha !== 'undefined' || !event.target.form) {
                return
            }

            let script = document.createElement('script');
            script.setAttribute('type', 'text/javascript');
            script.setAttribute('src', recaptchaUrl);
            document.head.appendChild(script);

            document.body.removeEventListener("input", loadRecaptchaScript);
            document.body.removeEventListener("focus", loadRecaptchaScript);
        }

        document.body.addEventListener("input", loadRecaptchaScript);
        document.body.addEventListener("focus", loadRecaptchaScript);

    }());

</script>
<?php endif; ?>
