<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

$siteKey = $storeConfig->getStoreConfig('recaptcha_frontend/type_recaptcha_v3/public_key');
?>
<?php if ($siteKey): ?>
    <?php if ($block->getData('render_script_tag')): ?>
    <script>
        <?php endif; ?>
        if (!this.hasCaptchaToken) {
            this.errors = 1;

            var $this = this;
            const recaptchaUrl = "https://www.google.com/recaptcha/api.js?render=<?= $escaper
                ->escapeHtmlAttr($siteKey) ?>";

            const executeGreCaptcha = () => {
                grecaptcha.ready(function () {
                    grecaptcha.execute(
                        '<?= $escaper->escapeHtml($siteKey) ?>',
                        {action: 'submit'}
                    ).then(function (token) {
                        var $recaptchaResponseInput = $form.querySelector('input[name="g-recaptcha-response"]');
                        if ($recaptchaResponseInput != null) {
                            $recaptchaResponseInput.value = token;
                            $this.errors = 0;
                            $this.hasCaptchaToken = 1;
                            $this.submitForm();
                        } else {
                            $this.errors = 1;
                            if ($this.setErrorMessages) {
                                $this.setErrorMessages(['<?= $escaper
                                    ->escapeHtml(__(
                                        'Your form does not have the required fields for recaptcha to work.'
                                    ))?>'])
                                $this.displayErrorMessage = true;
                            }
                        }
                    });
                })
            }

            if (typeof window.grecaptcha !== 'undefined') {
                executeGreCaptcha();
            } else {
                let script = document.createElement('script');
                script.setAttribute('type', 'text/javascript');
                script.setAttribute('src', recaptchaUrl);
                document.head.appendChild(script);

                script.addEventListener("load", executeGreCaptcha, false);
            }
        }
        <?php if ($block->getData('render_script_tag')): ?>
    </script>
<?php endif; ?>
<?php endif; ?>
