<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var $block Forgotpassword */
/** @var Forgotpassword $block */
/** @var Escaper $escaper */
?>
<div class="container mb-12">
    <div class="w-full md:w-1/2 card my-8">
        <form class="form password forget"
              action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate">
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($block->getLayout()->getBlock('captcha')->getData('form_id')) ?>" />
            <fieldset class="fieldset">
                <div class="text-secondary-darker mb-8"><?= $escaper->escapeHtml(
                        __('Please enter your email address below to receive a password reset link.')
                    ) ?></div>
                <div class="field email required">
                    <label for="email_address" class="label"><span><?= $escaper->escapeHtml(
                                __('Email')
                            ) ?></span></label>
                    <div class="control">
                        <input type="email" name="email" alt="email" id="email_address" class="form-input" required
                               value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary"><span><?= $escaper->escapeHtml(
                                __('Reset My Password')
                            ) ?></span></button>
                </div>
                <div class="secondary">
                    <a class="action back"
                       href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>"><span><?= $escaper->escapeHtml(
                                __('Go back')
                            ) ?></span></a>
                </div>
            </div>
        </form>
    </div>
</div>
