<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */


$availableLimitOptions = $block->getAvailableLimit();

?>

<?php if (count($availableLimitOptions) > 1): ?>
    <div class="field limiter flex items-center order-3 col-span-4 justify-center
                sm:col-span-2 sm:justify-end sm:order-2
                md:col-span-4 md:justify-center md:order-3
                lg:col-span-2 lg:justify-end lg:order-2"
    >
        <div class="control">
            <label class="text-sm label">
                <span><?= $escaper->escapeHtml((string)__('Show')) ?></span>

                <select data-role="limiter" class="form-select limiter-options"
                    @change="changeUrl(
                    'product_list_limit',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.limitDefault
                )">
                <?php foreach ($block->getAvailableLimit() as $key => $limit): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($key) ?>"
                        <?php if ($block->isLimitCurrent($key)): ?>
                            selected="selected"
                        <?php endif ?>>
                        <?= $escaper->escapeHtml($limit) ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </label>
        </div>
        <span class="limiter-text text-sm ml-2 sr-only">
        <?= $escaper->escapeHtml(__('per page')) ?>
    </span>
    </div>
<?php else: ?>
    <div class="field limiter flex">

    </div>
<?php endif;
