<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;

/** @var $block Toolbar */
?>
<div class="field limiter flex items-center">
    <label class="text-sm mr-2 label" for="limiter">
        <span><?= $block->escapeHtml(__('Show')) ?></span>
    </label>
    <div class="control">
        <select id="limiter" data-role="limiter" class="form-select limiter-options"
                @change="changeUrl('product_list_limit',event.currentTarget.options[event.currentTarget.selectedIndex].value,9)">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isLimitCurrent($_key)) :?>
                        selected="selected"
                    <?php endif ?>>
                    <?= $block->escapeHtml($_limit) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <span class="limiter-text text-sm ml-2"><?= $block->escapeHtml(__('per page')) ?></span>
</div>
