<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var $block Toolbar */
/** @var $escaper Escaper */

?>
<div class="field limiter flex items-center order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end">
    <span class="text-sm mr-2 label">
        <?= $escaper->escapeHtml(__('Show')) ?>
    </span>
    <div class="control">
        <select data-role="limiter"
                class="form-select limiter-options"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Show')) ?>"
                @change="changeUrl(
                    'product_list_limit',
                    event.currentTarget.options[event.currentTarget.selectedIndex].value,
                    options.limitDefault
                )">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit):?>
                <option value="<?= $escaper->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isLimitCurrent($_key)):?>
                        selected="selected"
                    <?php endif ?>>
                    <?= $escaper->escapeHtml($_limit) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <span class="limiter-text text-sm ml-2 sr-only">
        <?= $escaper->escapeHtml(__('per page')) ?>
    </span>
</div>
