<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;

/**  @var $block Toolbar */
?>
<?php if ($block->isEnabledViewSwitcher()) :?>
    <div class="modes inline-flex space-x-1 mr-2 items-center px-2 py-2 rounded-md border border-gray-300 bg-white text-sm leading-5 ">
        <?php $_modes = $block->getModes(); ?>
        <?php if ($_modes && count($_modes) > 1) :?>
            <strong class="modes-label sr-only" id="modes-label"><?= $block->escapeHtml(__('View as')) ?></strong>
            <?php foreach ($block->getModes() as $_code => $_label) :?>
                <?php if ($block->isModeActive($_code)) :?>
                    <strong title="<?= $block->escapeHtmlAttr($_label) ?>"
                            class="modes-mode active mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                            data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </strong>
                <?php else :?>
                    <a class="modes-mode mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?> opacity-25 hover:opacity-100"
                       title="<?= $block->escapeHtmlAttr($_label) ?>"
                       href="#"
                       @click.prevent="changeUrl('product_list_mode','<?= $block->escapeHtmlAttr(strtolower($_code)) ?>','')"
                       data-role="mode-switcher"
                       data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       id="mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>"
                       aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                        <span><?= $block->escapeHtml($_label) ?></span>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
