<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;

/** @var Escaper $escaper */

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php if (!$block->getCategory()) {
    return;
} ?>
<?php $_categories = $block->getCurrentChildCategories() ;?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count):?>
    <div class="card border border-container p-4 mx-6 md:mx-0 mb-8">
        <div class="title">
            <strong><?= $escaper->escapeHtml(__('Shop By')) ?></strong>
        </div>
        <div class="content">
            <strong class="subtitle"><?= $escaper->escapeHtml(__('Shopping Options')) ?></strong>
            <dl class="options" id="narrow-by-list2">
                <dt><?= $escaper->escapeHtml(__('Category')) ?></dt>
                <dd>
                    <ol class="items">
                        <?php /** @var \Magento\Catalog\Model\Category $_category */ ?>
                        <?php foreach ($_categories as $_category):?>
                            <?php if ($_category->getIsActive()):?>
                                <li class="item">
                                    <a href="<?= $escaper->escapeUrl($block->getCategoryUrl($_category)) ?>"
                                        <?php if ($block->isCategoryActive($_category)):?>
                                            class="current"
                                        <?php endif; ?>
                                    ><?= $escaper->escapeHtml($_category->getName()) ?></a>
                                    <span class="count"><?= $escaper->escapeHtml($_category->getProductCount()) ?></span>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
