<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;
use Hyva\Theme\ViewModel\ReCaptcha;

/** @var Subscribe $block */
/** @var Escaper $escaper */

/** @var ReCaptcha $recaptchaViewModel */
//Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency on
//Magento's Recaptcha module
$recaptchaViewModel = $block->getData('viewModelRecaptcha');
$recaptchaInputField = '';
$recaptchaLegalNotice = '';
if ($recaptchaViewModel !== null && $recaptchaData = $recaptchaViewModel->getRecaptchaData('newsletter')) {
    $recaptchaInputField = $block->getBlockHtml($recaptchaData[ReCaptcha::RECAPTCHA_INPUT_FIELD]);
    $recaptchaLegalNotice = $block->getBlockHtml($recaptchaData[ReCaptcha::RECAPTCHA_LEGAL_NOTICE_BLOCK]);
}
?>
<div class="lg:w-1/4 md:w-1/2 w-full px-4">
    <form class="form subscribe"
          action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
          method="post"
          x-data="initNewsletterForm()"
          @submit.prevent="submitForm()"
          id="newsletter-validate-detail">
        <div class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3 uppercase">
            <?= $escaper->escapeHtml(__('Newsletter')) ?>
        </div>
        <div class="flex xl:flex-nowrap md:flex-nowrap lg:flex-wrap flex-wrap justify-center md:justify-start">
            <label for="newsletter-subscribe" class="sr-only">
                <?= $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input name="email"
                type="email"
                required
                id="newsletter-subscribe"
                class="input input-light"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <button class="lg:mt-2 xl:mt-0 flex-shrink-0 inline-flex btn btn-primary">
                <?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>
            </button>
            <?= $recaptchaInputField ?>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="text-red flex items-center">
                                    <span class="inline-block w-8 h-8 mr-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                             stroke="currentColor">
                                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                        </svg>
                                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form>
    <div class="w-full">
    <?= $recaptchaLegalNotice ?>
    </div>
    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages: function setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm: function () {
                    var $form = document.querySelector('#newsletter-validate-detail');
                    <?= $block->getChildHtml('recaptcha_validation_newsletter'); ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>
