<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<script>
    function initSwatchOptions(swatchConfig) {
        return {
            swatchConfig,
            getAttributeSwatchData(attributeId) {
                const swatchConfig = Object.assign({}, this.swatchConfig[attributeId]);
                swatchConfig['details'] = JSON.parse(swatchConfig['additional_data']);

                return swatchConfig;
            },
            isTextSwatch(attributeId) {
                return this.getAttributeSwatchData(attributeId).details['swatch_input_type'] === 'text';
            },
            getSwatchBackgroundStyle(attributeId, itemId) {
                const config = this.swatchConfig[attributeId][itemId];

                if (this.isTextSwatch(attributeId)) {
                    return '';
                } else {
                    if (config.type.toString() === "1") {
                        return 'background-color:' + config.value;
                    } else if (config.type.toString() === "2") {
                        return "background: #ffffff url('" + config.value + "') no-repeat center";
                    }
                    return '';
                }
            },
            getSwatchConfig(attributeId, itemId) {
                return this.swatchConfig[attributeId][itemId];
            },
            activeTooltipItem: false,
            tooltipPositionElement: false,
            getTooltipImageStyle(attributeId, itemId) {
                const config = this.getSwatchConfig(attributeId, itemId);

                if (this.isTextSwatch(attributeId)) {
                    return '';
                } else {
                    if (config.type.toString() === "1") {
                        return 'background-color:' + config.value + '; width: 110px; height: 90px;';
                    } else if (config.type.toString() === "2") {
                        return "background: #ffffff url('" + config.thumb +
                            "') center center no-repeat; width: 110px; height: 90px;";
                    }
                    return '';
                }
            },
            getTooltipPosition() {
                return this.tooltipPositionElement ?
                    `top: ${this.tooltipPositionElement.offsetTop}px;` +
                    `left: ${
                        this.tooltipPositionElement.offsetLeft - (
                            this.tooltipPositionElement.closest('.snap') &&
                            this.tooltipPositionElement.closest('.snap').scrollLeft ||
                            0
                        )
                    }px;` : ''
            }
        }
    }
</script>
