<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

/** @var Template $block */

use Magento\Framework\View\Element\Template;

?>
<script>
    'use strict';
    {
        var private_content_key = 'mage-cache-storage';
        var private_content_expire_key = 'mage-cache-timeout';
        var private_content_version_key = 'private_content_version';

        var ttl = 3600;

        function getCookie(name) {
            var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
            return v ? v[2] : null;
        }

        function getBrowserStorage() {
            var browserStorage = window.localStorage || window.sessionStorage;
            if (!browserStorage) {
                return false;
            }
            try {
                browserStorage.setItem('storage_test', 1);
                browserStorage.removeItem('storage_test');
            } catch (e) {
                return false;
            }
            return browserStorage;
        }

        window.addEventListener('load', function () {
            var browserStorage = getBrowserStorage();
            if (!browserStorage) {
                typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                    [{
                        type: "warning",
                        text: "<?= $block->escapeHtml(__('Please enable LocalStorage in your browser.')) ?>"
                    }]
                );
                return;
            }
            try {
                var cookieVersion = getCookie(private_content_version_key);
                var storageVersion = browserStorage.getItem(private_content_version_key);

                var privateContentExpires = browserStorage.getItem(private_content_expire_key);
                if (privateContentExpires && new Date(privateContentExpires) < new Date()) {
                    browserStorage.removeItem(private_content_key);
                }

                if (cookieVersion && !storageVersion || cookieVersion !== storageVersion) {
                    fetchPrivateContent([]);
                    browserStorage.setItem(private_content_version_key, cookieVersion);
                } else if (cookieVersion && storageVersion && cookieVersion === storageVersion) {
                    var privateContent = JSON.parse(browserStorage.getItem(private_content_key));
                    if (privateContent && privateContentExpires) {
                        dispatchPrivateContent(privateContent);
                    } else {
                        fetchPrivateContent([]);
                    }
                }

            } catch (error) {
                console.warn('Error retrieving Private Content:', error);
            }
        });

        function dispatchPrivateContent(data) {
            var privateContentEvent = new CustomEvent("private-content-loaded", {
                detail: {
                    data: data
                }
            });
            window.dispatchEvent(privateContentEvent);
        }

        function fetchPrivateContent(sections) {
            fetch('<?= $block->escapeUrl(
                $block->getBaseUrl()
            ) ?>/customer/section/load/?sections=' + encodeURIComponent(
                sections.join(',')
            ), {
                method: 'GET',
                headers: {'Content-Type': 'application/json'},
            })
                .then(function (response) {
                    return response.json()
                })
                .then(
                    function (data) {
                        if (data) {
                            try {
                                var browserStorage = getBrowserStorage();
                                browserStorage.setItem(private_content_key, JSON.stringify(data));
                                browserStorage.setItem(private_content_expire_key, new Date(Date.now() + (ttl * 1000)).toISOString());
                            } catch (error) {
                                console.warn("Couldn't store privateContent", error);
                            }
                            dispatchPrivateContent(data);
                        }
                        console.log(data);
                    }
                );
        }
    }
</script>
