<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<!--
<script type="module" src="<?= $block->escapeUrl($block->getViewFileUrl('js/alpine-2.3.5.js')) ?>" defer="defer"></script>
<script nomodule src="<?= $block->escapeUrl($block->getViewFileUrl('js/alpine-ie11-2.3.5.js')) ?>" defer="defer"" defer></script>
-->

<script type="module" src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<script nomodule src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine-ie11.min.js" defer></script>

