<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
?>
<script>
    'use strict';
    function dispatchMessages(messages, hideAfter) {
        var messagesEvent = new CustomEvent("messages-loaded", {
            detail: {
                messages: messages,
                hideAfter: hideAfter
            }
        });
        window.dispatchEvent(messagesEvent);
    }
    {
        function initFormKey() {
            var inputSelector = 'input[name="form_key"]';
            var allowedCharacters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
            var length = 16;

            function generateRandomString() {
                var formKey = '';
                var charactersLength = allowedCharacters.length;
                for (var i = 0; i < length; i++) {
                    formKey += allowedCharacters[Math.round(Math.random() * (charactersLength - 1))]
                }
                return formKey;
            }

            var formKey = getCookie('form_key');

            if (!formKey) {
                formKey = generateRandomString();
                setCookie('form_key', formKey, 0);
            }
            Array.from(document.querySelectorAll(inputSelector)).map(function (input) {
                input.value = formKey
            });

        }

        function initMessages() {
            try {
                var messages = getCookie('mage-messages');
                messages = messages ? JSON.parse(decodeURIComponent(messages).replace(/\+/g, ' ')) : [];
                window.mageMessages = messages;
            } catch (error) {
                console.warn('Error parsing Cookie Messages:', error);
                return;
            }

            dispatchMessages(messages);


            deleteCookie('mage-messages');
        }

        function getCookie(name) {
            var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
            return v ? v[2] : null;
        }

        function setCookie(name, value, days) {
            var expires = '';

            if (days) {
                var d = new Date;
                d.setTime(d.getTime() + 24 * 60 * 60 * 1000 * days);
                expires = ";expires=" + d.toGMTString();
            }
            document.cookie = name + "=" + encodeURIComponent(value) +
                ";path=/" +
                expires;
        }

        function deleteCookie(name) {
            setCookie(name, '', -1);
        }

        window.addEventListener('load', function () {
            initFormKey();
            initMessages();
        })
    }
</script>
