<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Wigman Interactive. All rights reserved.
 * This product is licensed per Magento production install
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    var BASE_URL = '<?= /* @noEscape */ $block->getUrl('/') ?>';
    var THEME_PATH = '<?= /* @noEscape */ $block->getViewFileUrl('/') ?>';
</script>
